### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by frankvandenhurk** [azerty9971/xtend_tuya#1]
Hi,

Two questions:
- it is designed to replace the official Tuya plugin in my install or in combination with?
- would it be possible to make this available via HACS?

Thank you in advance,

Frank

**Comment by azerty9971** [comment]
Hello,
It's designed to be used in combination with the official tuya integration.
Regarding HACS I'm not really familiar with the procedure to do so, but why not

**Comment by azerty9971** [comment]
Hello,
I've made the request to be included in HACS, in the mean time, you can add this repo manually in your HACS sources and it will work :).

Have a nice evening,
Azerty
