### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by artzillla** [azerty9971/xtend_tuya#10]
Hello! 

It seems like this extension is not working anymore with the Tuya's latest security update. Looking at the official Tuya integration https://www.home-assistant.io/integrations/tuya, it says that now we need to enter "user code":

> You will need your User Code. You can find this code in the Smart Life app or Tuya Smart app in Settings > Account and Security screen, and enter the code shown on the User Code field.

This integration worked just fine before this update, however, currently I don't see any devices. It's worth noting that the official Tuya integration also stopped working until I entered that user code.

**Comment by azerty9971** [comment]
Hello,
I've updated the integration and it should work again with the new Tuya integration :).
Could you please test?

Have a nice day,
Azerty

**Comment by artzillla** [comment]
works now, thanks!
