### ISSUE TITLE
Support for Tuya EV Chargers (i.e. "Vevor")

### ISSUE THREAD

**Issue by cannondale0815** [azerty9971/xtend_tuya#106]
Hi Azerty, you mentioned in [this discussion](https://community.home-assistant.io/t/add-support-for-vevor-ev-charger-with-tuya-integration/647661) that you would look into adding support for Tuya based EV chargers to your HACS extension. Just leaving this here as a formal request :)

Diagnostics:

```
  "data": {
    "endpoint": "https://apigw.tuyaus.com",
    "terminal_id": "REMOVED -- DO YOU NEED IT?",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "REMOVED -- DO YOU NEED IT?",
    "name": "Car Charger",
    "category": "qccdz",
    "product_id": "w7lvyyxyevpwf20e",
    "product_name": "SS_US_7kW",
    "online": false,
    "sub": false,
    "time_zone": "-04:00",
    "active_time": "2024-09-20T17:33:05+00:00",
    "create_time": "2024-09-20T17:33:05+00:00",
    "update_time": "2024-09-20T17:33:05+00:00",
    "function": {
      "charge_cur_set": {
        "type": "Integer",
        "value": {
          "unit": "A",
          "min": 8,
          "max": 32,
          "scale": 0,
          "step": 1
        }
      },
      "work_mode": {
        "type": "Enum",
        "value": {
          "range": [
            "charge_now",
            "charge_pct",
            "charge_energy",
            "charge_schedule"
          ]
        }
      },
      "clear_energy": {
        "type": "Boolean",
        "value": {}
      },
      "switch": {
        "type": "Boolean",
        "value": {}
      }
    },
    "status_range": {
      "forward_energy_total": {
        "type": "Integer",
        "value": {
          "unit": "kW\u00b7h",
          "min": 0,
          "max": 99999999,
          "scale": 2,
          "step": 1
        }
      },
      "work_state": {
        "type": "Enum",
        "value": {
          "range": [
            "charger_free",
            "charger_insert",
            "charger_free_fault",
            "charger_wait",
            "charger_charging",
            "charger_pause",
            "charger_end",
            "charger_fault"
          ]
        }
      },
      "charge_cur_set": {
        "type": "Integer",
        "value": {
          "unit": "A",
          "min": 8,
          "max": 32,
          "scale": 0,
          "step": 1
        }
      },
      "sigle_phase_power": {
        "type": "Integer",
        "value": {
          "unit": "kW",
          "min": 0,
          "max": 99999999,
          "scale": 3,
          "step": 1
        }
      },
      "power_total": {
        "type": "Integer",
        "value": {
          "unit": "kW",
          "min": 0,
          "max": 99999999,
          "scale": 3,
          "step": 1
        }
      },
      "connection_state": {
        "type": "Enum",
        "value": {
          "range": [
            "controlpi_12v",
            "controlpi_12v_pwm",
            "controlpi_9v",
            "controlpi_9v_pwm",
            "controlpi_6v",
            "controlpi_6v_pwm",
            "controlpi_error"
          ]
        }
      },
      "work_mode": {
        "type": "Enum",
        "value": {
          "range": [
            "charge_now",
            "charge_pct",
            "charge_energy",
            "charge_schedule"
          ]
        }
      },
      "clear_energy": {
        "type": "Boolean",
        "value": {}
      },
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "temp_current": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": -40,
          "max": 200,
          "scale": 0,
          "step": 1
        }
      },
      "charge_energy_once": {
        "type": "Integer",
        "value": {
          "unit": "kW\u00b7h",
          "min": 1,
          "max": 999999,
          "scale": 2,
          "step": 1
        }
      }
    },
    "status": {
      "forward_energy_total": 0,
      "work_state": "charger_free",
      "charge_cur_set": 16,
      "sigle_phase_power": 0,
      "power_total": 0,
      "connection_state": "controlpi_12v",
      "work_mode": "charge_now",
      "clear_energy": true,
      "switch": false,
      "temp_current": 31,
      "charge_energy_once": 942
    },
    "home_assistant": {
      "name": "Car Charger",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    },
    "set_up": false,
    "support_local": true
  }
```

**Comment by azerty9971** [comment]
Hello,
By any chance would it be possible to share the device with me?
It's way easier for me to implement it this way :).

If that's OK, can you share it with my Tuya/Smartlife account devun999999@gmail.com
(you have to do that from the app itself :))

Thanks in advance,
Azerty

**Comment by cannondale0815** [comment]
Will do -- what's your region/country? SmartLife is asking me for that when
trying to share with you.

Also note that the device isn't constantly connected, so you may only see
it online sporadically, usually during normal US working hours.

Thanks, I appreciate it!

**Comment by azerty9971** [comment]
Hello, my country is Belgium :).

No worries, even offline I should be able to get the infos from the cloud ;)

**Comment by cannondale0815** [comment]
I just tried and unfortunately it doesn't allow me to share my device with
someone in a different region. Can you perhaps create a dummy USA account
for yourself?

**Comment by azerty9971** [comment]
Hello,
Could you retry with:
devun999999.us@gmail.com ?

Thanks in advance,
Azerty

**Comment by cannondale0815** [comment]
That worked and I shared it with you, thank you! Let me know what else I
can do to help.

**Comment by cannondale0815** [comment]
@azerty9971 FYI, the device is online for the next few hours while my wife is charging our 2023 Prius Prime at work. No rush and no pressure from my end at all, just an FYI.

**Comment by azerty9971** [comment]
Hello,
Really sorry for the delay but last week was super busy :/.

I''ve made the implementation in the latest BETA build, can you please update to it and let me know if everything works as expected?

Also, some texts were quite cryptic to me, so if you have things that are mistranslated don't hesitate to point them out to me and I'll fix them :).

Have a nice day,
Azerty

**Comment by cannondale0815** [comment]
There is no need to apologize. You are doing voluntary work for the benefit of the community, and that is always appreciated. Thank you so much for this, I will test it today/tomorrow and report back! :)

**Comment by cannondale0815** [comment]
Good news, your latest beta 16 added new entities to the device! I haven't plugged in the device yet to observe functionality, but this looks great already! I will report back once we tried charging the car, likely sometime tomorrow. Thank you @azerty9971 !

![Screenshot 2024-10-07 102418](https://github.com/user-attachments/assets/69cab823-9256-494d-a4e9-54cbfa724410)

**Comment by azerty9971** [comment]
That is strange, on my side I see them:
![image](https://github.com/user-attachments/assets/0e7748c0-d3f5-48b1-a37c-130b746a7c67)

Is it possible that it just took a bit of time to report the online status?

**Comment by cannondale0815** [comment]
Oh, I just restarted HA once more and now it's all there! Yay! :)

My wife will try charging tomorrow and I'll keep an eye out for the various charge states and report back -- thank you!!!

**Comment by cannondale0815** [comment]
@azerty9971 So we unplugged the device for the past ten hours, but in HA, I still see all the previous entity values. It seems it doesn't update it unless I reboot HA (which is what I had to do yesterday). Should I be using Xtend_Tuya with a different authentication method perhaps (i.e. not alongside Tuya)?

**Comment by azerty9971** [comment]
Hello,
Before you mess with the credentials, I'd like to test something out :).

Can you update to the latest beta and let me know if the device now correctly shows its online/offline status?

Thanks in advance,
Azerty

**Comment by cannondale0815** [comment]
Thank you! I installed the new beta 18 and am waiting for my wife to return from work, so I can test it with the charger :)   Will report back!

**Comment by cannondale0815** [comment]
@azerty9971 So I plugged the charger back into an outlet and I can again see that it shows up in the SmartLife app, but all the entities in HA are still "unavailable" in beta 18. Presumably, once I restart HA, they would show up again.

**Comment by azerty9971** [comment]
https://meet.google.com/svs-jxiy-kay
