### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by mvrk69** [azerty9971/xtend_tuya#11]
Hi,

When i try to use it i get this error:

Config flow could not be loaded: {"message":"Invalid handler specified"}

**Comment by azerty9971** [comment]
Hello,
I'm currently very busy but I'll try to have a look at the issues soon :).

Sorry for the delay,
Azerty

**Comment by azerty9971** [comment]
Hello,
I've updated the integration and it should work again with the new Tuya integration :).
Could you please test?

Have a nice day,
Azerty

**Comment by mvrk69** [comment]
Hi, yes, now works fine.

Thank you.
