### ISSUE TITLE
Add more support for WiFi Duo LED Light WFD 3050 P

### ISSUE THREAD

**Issue by HBK1** [azerty9971/xtend_tuya#114]
Hi

I have sent diag json and shared a device WFD 3050 with devun999999@gmail.com
Would be grateful if you could make the PIR and switching to/from auto mode working.

**Comment by azerty9971** [comment]
Hello,
Sorry for the delay, this has been done :).

It will be available in the next release (which is planned for today :)).

Have a nice evening,
Azerty

**Comment by azerty9971** [comment]
Hello,
this change has been included in the stable release of v3.0.0.

Have a nice evening,
Azerty

**Comment by HBK1** [comment]
Thankyou, it works perfect!
