### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by tnjgb** [azerty9971/xtend_tuya#12]
Xtend_tuya seems to have stopped working today. It stopped loading so I have reinstalled it and it is now loading but it is not seeing any Tuya devices.

In addition all my Tuya UP111_RTL sockets reset to default and I had to re-enable the Voltage Current and Power sensors but now the Energy sensor is no longer there on Home Assistant but is in the Smart Life app. No other Tuya devices were affected.

**Comment by azerty9971** [comment]
Hello,
I'm currently very busy but I'll try to have a look at the issues soon :).

Sorry for the delay,
Azerty

**Comment by nelscougar** [comment]
same for me...I had to re-enable the Voltage Current and Power sensors but now the Energy sensor is no longer there

**Comment by azerty9971** [comment]
Hello,
I've updated the integration and it should work again with the new Tuya integration :).
Could you please test?

Have a nice day,
Azerty

**Comment by tnjgb** [comment]
Hi,

Thanks the integration now works fine. There must be quicker way to reinstall but I deleted every custom file and folder under xtend_tuya then uploaded every single new file one at a time using file editor.

Regards,

Tom

**Comment by azerty9971** [comment]
Personally I've cloned the git repository inside the custom_component folder, this way the update is a simple "git pull" ;).

This version auto configures itself too based on your tuya integration settings...

Have a nice day,
Azerty
