### ISSUE TITLE
Update frequency for water level sensor too high (every second)

### ISSUE THREAD

**Issue by quackelduck** [azerty9971/xtend_tuya#149]
I‘m using the extended Tuya to work with a tank level sensor I installed in my drainage shaft.

Device info
Brand: EPT Tech
Model: Smart TLC2206

All works so far so good, however: it keeps updating about EVERY second which slows my statistics and spams my log-file. And also wifi/internet etc.

Is there a way to reduce this?

i couldn‘t find anything in the Tuya app or on the device.

**Comment by azerty9971** [comment]
Hello,
What could be causing this is if you are also using localtuya to update the sensor of the device. Otherwise if you are not using localtuya, then it means that the device is itself sending updates every seconds and there is nothing you can do about it...

**Comment by quackelduck** [comment]
Tried both, Local Tuya as well as „regular“ Tuya… same story in both cases. Thanks!
