### ISSUE TITLE
Human Presence Detection detected correctly, but not showing motion/presence status - RTCZ-03T

### ISSUE THREAD

**Issue by prashantchawla** [azerty9971/xtend_tuya#165]
I purchased the 24GHz presence sensor from aliexpress (ref: [https://www.aliexpress.com/item/1005006959313783.html](https://www.aliexpress.com/item/1005006959313783.html)) (Probably similar to [https://github.com/azerty9971/xtend_tuya/issues/105](https://github.com/azerty9971/xtend_tuya/issues/105) )

In the integration, I can see from debug json that status "presence_state" is correctly being updated (even without Tuya Cloud creds) as "large_move" or "none" respectively when presence is detected/not detected. However, the entity always keeps showing as 'Away'.

The correct presence status is the priority, but other entities like ldr/luminosity could be nice if integrated as well (only work after Tuya Cloud creds are added).

Diagnostics - [xtend_tuya-28afe12c083fbf75867dfc3e0df61c03-Human presence detector-f8f6c971305322e7423451f4eb5d54be.json](https://github.com/user-attachments/files/17966941/xtend_tuya-28afe12c083fbf75867dfc3e0df61c03-Human.presence.detector-f8f6c971305322e7423451f4eb5d54be.json)

Thank you so much for your efforts in maintaining this project!

**Comment by prashantchawla** [comment]
I think this is fixed in core as part of [this ](https://github.com/home-assistant/core/pull/129801) PR already. Closing this here, thanks!

**Comment by azerty9971** [comment]
Is it already in the latest HA?

Sorry for the answer delay, my life is very messy these days and I didn't have much time to work on this project :'(

Glad it was fixed upstream :)

**Comment by prashantchawla** [comment]
No worries at all @azerty9971, I was just writing a fix for this taking reference from the code in the tuya core component, when I found it out. Let me know if you need help with anything - I can contribute some time.

Just updated to HA 2024.12.1 - includes the fix.
