### ISSUE TITLE
Tuya integration + Xtend Tuya = broken

### ISSUE THREAD

**Issue by sharpsan** [azerty9971/xtend_tuya#168]
I am using the official Tuya package + Xtend Tuya.  Aftering adding Xtend, devices that previously worked no longer work - example: toggling lights no longer work; you can switch them on, but the "on" state is no longer recognized.  Removing this package fixes the problem.  Please let me know if any additional info is needed.

### Error log:
```
This error originated from a custom integration.

Logger: tuya_sharing
Source: custom_components/xtend_tuya/multi_manager/tuya_sharing/init.py:179
integration: Xtend Tuya (documentation, issues)
First occurred: 12:56:41 AM (4 occurrences)
Last logged: 12:56:41 AM

on message error = MultiDeviceListener.update_device() takes 2 positional arguments but 3 were given
```

**Comment by stilldazed25** [comment]
I have the same issue

**Comment by azerty9971** [comment]
Hello,
Can you post your system logs regarding this?

Go to "Settings" bottom left then -> "System" -> "Logs".
You should see an error about this, can you post it here please?

Thanks in advance,
Azerty

**Comment by sharpsan** [comment]
There were no relevant system logs.  I had to temporarily enable logging for the package to get the one I sent with the original post.

**Comment by azerty9971** [comment]
Hello,
Can you try the latest stable version please?

This should resolve this issue :).

Have a nice day,
Azerty

**Comment by sharpsan** [comment]
This seems to have fixed it.  Thanks!
