### ISSUE TITLE
Temperature electric quantity controller missing energy parametrs

### ISSUE THREAD

**Issue by artkron** [azerty9971/xtend_tuya#17]
![image](https://github.com/azerty9971/xtend_tuya/assets/170014685/6b89a62a-5658-4fd1-b3c7-0c2e95428506)
Hello, thank you for work!
In this device missing electircal parametrs.
https://aliexpress.ru/item/1005005033605161.html
[1.json](https://github.com/user-attachments/files/15685791/1.json)
[Standard Instruction Set.txt](https://github.com/user-attachments/files/15685858/Standard.Instruction.Set.txt)

**Comment by azerty9971** [comment]
Hello,
This should be added in the latest commit. Can you please update?

Thanks,
Azerty9971

**Comment by artkron** [comment]
Hello!
Yes. Now "energy" exist. Theank you!
This device also has parameters for mains voltage, current consumption, power. The standard tuya integration does not have these parameters either. Is it possible to receive these parameters as well?
![image](https://github.com/azerty9971/xtend_tuya/assets/170014685/99331afe-75db-4d6a-aab9-67ecab31d83a)

**Comment by azerty9971** [comment]
Hello,
The additional parameters should be dealt with by the regular Tuya integration, I'll make a pull request to the official one to add support for your device ;)

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
While I'm at it, are there other sensors that you would like to see available?

If so, send me an email at devun999999@gmail.com and we'll do the testing together :)

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
The PR has been merged in the HA core repository, I expect it to be available as from the next update.
Once it's done, can you verify and let me know if everything is working as expected?

Have a nice day,
Azerty

**Comment by artkron** [comment]
azerty9971, ok, i tell you. Waiting for update. Thank you

**Comment by artkron** [comment]
Hello.
I am update HA to version 2024.6.4, but no changes in tuya integration.
Also i reinstall standard tuya integration. Now electrical parameters not present

**Comment by artkron** [comment]
Hello [azerty9971](https://github.com/azerty9971)!
In the version 2024.7.0 i can see voltage, current and power!
Thank you very match!

![image](https://github.com/azerty9971/xtend_tuya/assets/170014685/33858069-fbc5-4a8d-ba5b-09bae5bcbf02)

**Comment by azerty9971** [comment]
Glad I could help ;)
