### ISSUE TITLE
less information on the smart litter box

### ISSUE THREAD

**Issue by d4nm0** [azerty9971/xtend_tuya#177]
Hi, there,
I'm on version 3.0.7 of the integration and I don't have as much information as before.
![image](https://github.com/user-attachments/assets/8b5a2884-b0cd-4d86-af9d-e15242d8ef71)

**Comment by azerty9971** [comment]
Hello Dan,
Can you check if this applies to you?
https://github.com/azerty9971/xtend_tuya/blob/main/docs/renew_cloud_credentials.md

Otherwise join me on https://meet.google.com/qqj-nxcp-dku

Have a nice day,
Azerty

**Comment by d4nm0** [comment]
I had not seen the doc. It works like a charm thanks :)

**Comment by azerty9971** [comment]
Heureux d'avoir pu aider :).

Si tu n'as rien d'autre à faire tu peux me rejoindre sur le Google Meet pour papoter ;)

Bonne soirée,
Azerty
