### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by TobiasPSP** [azerty9971/xtend_tuya#22]
I am very curious about your tuya extension. I am no Linux guy though. Although I am running HA on Raspberry Pi 5, I have no idea how I could copy files to the location you mention. 

I know this is more an ask for a hint than an issue but probably there are many more users like me. Could you maybe update your installation instructions so users with no Linux background feel well? Are you planning on making this integration available via HACS maybe?

Many thanks for your great work!

**Comment by TobiasPSP** [comment]
Apparently installation is much easier than I thought: I added your github repo to HACS as a custom repository and was then able to simply download and extract the integration to the right place. 

Maybe this helps someone. Great work - many thanks. Right after installing the integration, I was able to finally show the energy consumption readings for all my Tuya devices.

**Comment by azerty9971** [comment]
Hello Tobias,
Yes, I've made this repo compatible with HACS (and I'm waiting for it to be approved in their main repository so that people won't have to add it manually).

I'll update the README so that this is more clear ;).

Have a nice day,
Azerty
