### ISSUE TITLE
login_error

### ISSUE THREAD

**Issue by csomyy** [azerty9971/xtend_tuya#3]
I got a "login_error" message no matter how accurate i copy my credentials to the 'Add integration' communication box.
I checked my data and are correct.
Any tips, tricks here?

**Comment by csomyy** [comment]
I got this. Sorry.

**Comment by azerty9971** [comment]
What was the issue?

Tuya's IoT cloud license expired?

Have a nice day !!

**Comment by csomyy** [comment]
I was trying to input my Tuya IOT username, not the Tuya Smarthome app username.
