### ISSUE TITLE
not correct consumption from ZBP-1G (zigbee with power meter) 

### ISSUE THREAD

**Issue by Djohnypalace** [azerty9971/xtend_tuya#32]
not correct read consumption
![photo_2024-06-29_10-42-45](https://github.com/azerty9971/xtend_tuya/assets/16336282/8a6a793f-5913-49db-a9ef-cf3a8ab55ff5)
![Записати](https://github.com/azerty9971/xtend_tuya/assets/16336282/2b7a40a7-b2e4-4596-b797-7a4b887e5a69)

**Comment by azerty9971** [comment]
Hello,
Can you send me the diagnostic information please?
In your device page, click the download diagnostic ;).

Have a nice day,
Azerty

**Comment by Djohnypalace** [comment]
[tuya-70d8e2b956c738ea68bce5912def0f51-Вітальня ближня-09389c55cad15cd99f9ed00c511b624d.json](https://github.com/user-attachments/files/16039264/tuya-70d8e2b956c738ea68bce5912def0f51-.-09389c55cad15cd99f9ed00c511b624d.json)

**Comment by azerty9971** [comment]
Hello,
Can you update to the latest release of Xtend_tuya and let me know if that fixed it for you?

Thanks :)
Azerty

**Comment by Djohnypalace** [comment]
![3300624](https://github.com/azerty9971/xtend_tuya/assets/16336282/668d8acf-69a0-4948-888f-9101e9f0e020)
[home-assistant_xtend_tuya_2024-06-30T12-55-38.335Z.log](https://github.com/user-attachments/files/16044703/home-assistant_xtend_tuya_2024-06-30T12-55-38.335Z.log)

**Comment by azerty9971** [comment]
Hello,
That is really strange, I've never had this error before oO.

Could you try the following:
Remove the configuration entry from the Xtend Tuya configuration page (the one in your screenshot above)
Do the same with the Tuya one
Reconfigure the Tuya integration with your credentials (the QR code...)
Re-add the Xtend Tuya integration and let me know if it works?

I think that somehow your regular Tuya integration is still using the old method of cloud authentication (which I thought was impossible to be honest)

**Comment by azerty9971** [comment]
By any chance, do you have a custom version of the Tuya integration installed (when you click on your regular Tuya integration, do you see the "Custom integration" yellow box)?

**Comment by azerty9971** [comment]
Oh, I just figured out that you currently don't use the Tuya integration at all, please do the following to fix it (for now, I'll make it work in the future):

Go to Settings -> Device and services -> Click the green button "Add integration" at the bottom right -> search for "Tuya" and add the scan the QR code using the SmartLife app on your phone.

Then either restart HomeAssistant or go to the Xtend tuya page and hit "Reload configuration" next to your username

**Comment by azerty9971** [comment]
Disregard my other comments, I think I've figured out what is happening better.

Wait a few minutes, there will be a release available through HACS :).

Have a nice day,
Azerty

**Comment by Djohnypalace** [comment]
finally restored. After the deleted messages, I deleted the CA along with the VM and reinstalled it, then restored the backup and updated the integration and everything worked. Now I'm looking for a way to clear  history sensor.spalnia_blizhnia_consumption and other zigbee (It’s good that out of 20 I have replaced only 2 wifi on zigbee. so far, 18 wifi are waiting for replacement )

**Comment by azerty9971** [comment]
Normally the device values will reset automatically on next cloud push.

Just wait a couple of hours and it should be good ;).

Can you confirm that all is working as expected?

Have a nice day,
Azerty

**Comment by Djohnypalace** [comment]
> Normally the device values will reset automatically on next cloud push.
> 
> Just wait a couple of hours and it should be good ;).
> 
I hope 
> Can you confirm that all is working as expected?
of course, as soon as the indicators change, I will write - good or bad
> 
> Have a nice day, Azerty
a quiet and peaceful day Alexey

**Comment by Djohnypalace** [comment]
not correct read :(

**Comment by Djohnypalace** [comment]
don't work 
![300624](https://github.com/azerty9971/xtend_tuya/assets/16336282/565f424d-f112-4926-b3b0-2e2ae17db5b1)
0.39 kWh in real

**Comment by azerty9971** [comment]
Could it be that the unit is not correct?
In what unit is your sensor?

Can you provide me with a 2 diagnostics for the same power meter with 1h difference between them please?

Sorry for the headache :'(.

Thanks in advance,
Azerty

**Comment by Djohnypalace** [comment]
maybe I was wrong. I restored from a backup and did not update the version. I deleted it, it seemed like I cleared the history and.... turned off the light. I'm from Ukraine. As soon as the lights are turned on, I will send new diagnostics by installing the latest version from Github

**Comment by azerty9971** [comment]
that could be it indeed ;)

What I need to see is if the consumption graph keeps growing or if it goes up and down with the new version.

Because ADD_ELE is supposed to be the delta energy between 2 consumptions (meaning, if AT 1PM you had spent 10kWh and at 2PM you were at 12kWH then ADD_ELE should be 2kWh). But it looks like your model is sending the total consumption every time so I had to change the logic so that we don't add up each cloud update.

I hope you are not too impacted by the war and pray that everything is fine for you and your loved ones!
Azerty

**Comment by Djohnypalace** [comment]
[home-assistant_xtend_tuya_2024-06-30T12-55-38.335Z.log](https://github.com/user-attachments/files/16046045/home-assistant_xtend_tuya_2024-06-30T12-55-38.335Z.log)

**Comment by Djohnypalace** [comment]
![300624-1](https://github.com/azerty9971/xtend_tuya/assets/16336282/71c0a8e4-5398-4423-a4b4-f17c6a953ed6)
[xtend_tuya-70ac4853c51f275cb823b9343be186ec-Спальня ближня-068a9d9a0b1956723e0ca1a4ea3f303f.json](https://github.com/user-attachments/files/16046053/xtend_tuya-70ac4853c51f275cb823b9343be186ec-.-068a9d9a0b1956723e0ca1a4ea3f303f.json)
![Uploading photo_2024-06-30_23-20-29.jpg…]()

**Comment by Djohnypalace** [comment]
![photo_2024-06-30_23-24-12](https://github.com/azerty9971/xtend_tuya/assets/16336282/c53b052d-0b78-4859-a923-d5854fce4f8a)
[xtend_tuya-70ac4853c51f275cb823b9343be186ec-Вітальня ближня-09389c55cad15cd99f9ed00c511b624d (1).json](https://github.com/user-attachments/files/16046063/xtend_tuya-70ac4853c51f275cb823b9343be186ec-.-09389c55cad15cd99f9ed00c511b624d.1.json)
![Записати](https://github.com/azerty9971/xtend_tuya/assets/16336282/ba8770ab-9c08-4248-90b8-bc1160f0e1cd)

**Comment by Djohnypalace** [comment]
If I can't sleep I'll do it again in an hour

**Comment by Djohnypalace** [comment]
[tuya-70d8e2b956c738ea68bce5912def0f51-Вітальня ближня-09389c55cad15cd99f9ed00c511b624d.json](https://github.com/user-attachments/files/16046258/tuya-70d8e2b956c738ea68bce5912def0f51-.-09389c55cad15cd99f9ed00c511b624d.json)
[tuya-70d8e2b956c738ea68bce5912def0f51-Спальня ближня-068a9d9a0b1956723e0ca1a4ea3f303f (1).json](https://github.com/user-attachments/files/16046259/tuya-70d8e2b956c738ea68bce5912def0f51-.-068a9d9a0b1956723e0ca1a4ea3f303f.1.json)
[tuya-70d8e2b956c738ea68bce5912def0f51-Спальня ближня-068a9d9a0b1956723e0ca1a4ea3f303f.json](https://github.com/user-attachments/files/16046260/tuya-70d8e2b956c738ea68bce5912def0f51-.-068a9d9a0b1956723e0ca1a4ea3f303f.json)
[xtend_tuya-70ac4853c51f275cb823b9343be186ec-Вітальня ближня-09389c55cad15cd99f9ed00c511b624d.json](https://github.com/user-attachments/files/16046261/xtend_tuya-70ac4853c51f275cb823b9343be186ec-.-09389c55cad15cd99f9ed00c511b624d.json)
[xtend_tuya-70ac4853c51f275cb823b9343be186ec-Спальня ближня-068a9d9a0b1956723e0ca1a4ea3f303f (1).json](https://github.com/user-attachments/files/16046262/xtend_tuya-70ac4853c51f275cb823b9343be186ec-.-068a9d9a0b1956723e0ca1a4ea3f303f.1.json)
[xtend_tuya-70ac4853c51f275cb823b9343be186ec-Спальня ближня-068a9d9a0b1956723e0ca1a4ea3f303f.json](https://github.com/user-attachments/files/16046263/xtend_tuya-70ac4853c51f275cb823b9343be186ec-.-068a9d9a0b1956723e0ca1a4ea3f303f.json)

**Comment by azerty9971** [comment]
This looks better already,
can you confirm that the consumption graphs are only going up since the upgrade?
Normally, the value should match what you have in the Tuya app, can you confirm?

**Comment by Djohnypalace** [comment]
![photo_2024-07-01_00-34-21](https://github.com/azerty9971/xtend_tuya/assets/16336282/22e42c2d-c286-4c1c-b1e4-b57bbe0fe653)
![photo_2024-07-01_00-34-32](https://github.com/azerty9971/xtend_tuya/assets/16336282/8c419e8b-cf62-4a47-ad6c-bff5a9581bf2)
![1](https://github.com/azerty9971/xtend_tuya/assets/16336282/85f4602c-8782-462d-89d2-960000ce2852)
![2](https://github.com/azerty9971/xtend_tuya/assets/16336282/34ece8c9-2411-4ff7-a8a7-6faec3221873)

**Comment by azerty9971** [comment]
I think this is now correct, 2.09kWh looks like it's matching the reported value in your app.

Maybe try to reset the consumption in your app or give it a few days and see if the values are still aligned (they should be)

**Comment by Djohnypalace** [comment]
,I hope the problem is completely resolved. Will you close this topic as resolved or will I? Thanks again!

**Comment by azerty9971** [comment]
Let's wait a few days and verify that all is indeed working as expected ;)

**Comment by BalooDK** [comment]
My consumption numbers are way off, on this release. Most of my switches shows extremely low consumption, and one shows a crazy high number

**Comment by BalooDK** [comment]
I had the manually installed version 1.0 until yesterday. 
I uninstalled that version completely, and installed the HACS version 1.2.6.

This is what I got on TV Soveværelse

As you can see, I used 5 kWh in my whole house today. TV Soveværelse shows 6 kWh. Tuya app shows 0.13 kWH

![IMG_0465](https://github.com/azerty9971/xtend_tuya/assets/5202479/51078eaa-17e4-4077-b246-7750f311f594)
![IMG_0467](https://github.com/azerty9971/xtend_tuya/assets/5202479/05fe156e-d497-48bf-b604-6c7b5d1e7c0f)
![IMG_0466](https://github.com/azerty9971/xtend_tuya/assets/5202479/0eeb1554-e031-44d4-b7ad-b0dd26c6c587)
![IMG_0468](https://github.com/azerty9971/xtend_tuya/assets/5202479/1fb07033-86ea-4131-af9a-8edfe94c54ac)

[tuya-8bc965e54273aa45c7fd0f7fe8ac3f35-TV Soveværelse-55dfa1cf96fd63367a55898f4fb29e7a.json](https://github.com/user-attachments/files/16088967/tuya-8bc965e54273aa45c7fd0f7fe8ac3f35-TV.Sovevaerelse-55dfa1cf96fd63367a55898f4fb29e7a.json)

[xtend_tuya-27ffcd17e4f5aa8c82799f44c9b9b5b9-TV Soveværelse-55dfa1cf96fd63367a55898f4fb29e7a.json](https://github.com/user-attachments/files/16089102/xtend_tuya-27ffcd17e4f5aa8c82799f44c9b9b5b9-TV.Sovevaerelse-55dfa1cf96fd63367a55898f4fb29e7a.json)

Don't know if this is what you asked for ;)

**Comment by BalooDK** [comment]
This is one with too low consumption

![IMG_0469](https://github.com/azerty9971/xtend_tuya/assets/5202479/cdbd578a-a3c0-49d0-bab3-c77c59c94831)
![IMG_0470](https://github.com/azerty9971/xtend_tuya/assets/5202479/56128722-83cc-4f35-8553-73379187a31e)

[xtend_tuya-27ffcd17e4f5aa8c82799f44c9b9b5b9-Teknik-76faec089c3035cd94418161c6cf2373.json](https://github.com/user-attachments/files/16089151/xtend_tuya-27ffcd17e4f5aa8c82799f44c9b9b5b9-Teknik-76faec089c3035cd94418161c6cf2373.json)

[tuya-8bc965e54273aa45c7fd0f7fe8ac3f35-Teknik-76faec089c3035cd94418161c6cf2373.json](https://github.com/user-attachments/files/16089154/tuya-8bc965e54273aa45c7fd0f7fe8ac3f35-Teknik-76faec089c3035cd94418161c6cf2373.json)

**Comment by BalooDK** [comment]
Seems like you are correct. The last step (0.57 kWh) equals the total of the device

**Comment by BalooDK** [comment]
It's not even the full day. It's the device total

**Comment by BalooDK** [comment]
I just verified that it is the device total. The Robotstøvsuger is connected to the same brand of Zigbee plug, and the last step of the graph also matches the device total.

The plugs with thee low consumption measurement are wifi plugs, but still the same brand as the Zigbee plugs

**Comment by azerty9971** [comment]
Hello,
Could you try with the latest beta version?

Please make sure to configure a Tuya IOT platform account (like for the old Tuya integration) using the "Configure" button in the Xtended Tuya configuration page:
![image](https://github.com/azerty9971/xtend_tuya/assets/3135352/8fb22ce4-1b61-405e-a461-71d1f4c5c391)
To use this new feature, go to the integration page then next to your username hit "configure":
You'll be prompted with the exact same window as the previous Tuya integration.
To retrieve the information, you have to follow this guide:
0- Before you start, in the IOT platform make sure that you selected the data center of your region on the top right (IMPORTANT)
1- Configure your Tuya IOT platform developer account: https://developer.tuya.com/en/docs/iot/Platform_Configuration_smarthome?id=Kamcgamwoevrx
2- Input the required credentials: https://developer.tuya.com/en/docs/iot/Home-assistant-tuya-intergration?id=Kb0eqjig0utdd

Once it's configured, I recommend to restart Home Assistant (in theory it's not needed but it's safer since this is an early beta).

**Comment by BalooDK** [comment]
Oh… i already updated 😜 It’s been running for 4 or 5 hours. Doesn’t get any data

**Comment by azerty9971** [comment]
The latest beta should fix it ;)

After installing it give it a bit of time to get the sensor updates ;)

**Comment by BalooDK** [comment]
Thank you. Now the plugs with the very high consumption are spot on 👍🏻
The other plugs still have weird readings. 

![IMG_0487](https://github.com/azerty9971/xtend_tuya/assets/5202479/70965ad8-0931-4002-87d4-13b42b5c4616)


![IMG_0486](https://github.com/azerty9971/xtend_tuya/assets/5202479/166b1972-0c01-4424-b33a-27adf331fc22)


![IMG_0485](https://github.com/azerty9971/xtend_tuya/assets/5202479/baa2c806-8541-4b6c-9208-422ff4dc7bc6)


![IMG_0484](https://github.com/azerty9971/xtend_tuya/assets/5202479/7bbf9607-2bd5-40df-939e-88f34f13c725)


![IMG_0483](https://github.com/azerty9971/xtend_tuya/assets/5202479/a118d67c-48d2-4214-bee2-14a5b6af07dc)

**Comment by azerty9971** [comment]
Hello,
Would it be possible for you to share one of the devices that misbehaves with me?
If so, could you share your device with my tuya/smart life account devun999999@gmail.com 

This way I'll be able to get what the cloud is sending as debug :).

Thanks in advance,
Azerty

**Comment by BalooDK** [comment]
Shared my fridge. Please don’t turn it off 😜

**Comment by azerty9971** [comment]
Nice, can you also give me the diagnostic information (on the device page in HA) for this specific device?

Thanks :)

**Comment by BalooDK** [comment]
[tuya-8bc965e54273aa45c7fd0f7fe8ac3f35-Køleskab-6d65bd441cf5dea93a7af7df4e4d789c.json](https://github.com/user-attachments/files/16170722/tuya-8bc965e54273aa45c7fd0f7fe8ac3f35-Koleskab-6d65bd441cf5dea93a7af7df4e4d789c.json)
[xtend_tuya-27ffcd17e4f5aa8c82799f44c9b9b5b9-Køleskab-6d65bd441cf5dea93a7af7df4e4d789c.json](https://github.com/user-attachments/files/16170723/xtend_tuya-27ffcd17e4f5aa8c82799f44c9b9b5b9-Koleskab-6d65bd441cf5dea93a7af7df4e4d789c.json)

**Comment by BalooDK** [comment]
Any news on this ?

**Comment by azerty9971** [comment]
Hello,
The initial testing done with the latest release look better to me.
When I compare the full day of consumption in the Tuya App and in the energy dashboard I'm very close...

Can you verify if it looks better with the latest version of XT?

Thanks :)

**Comment by BalooDK** [comment]
Nah... it's close to double of the consumption ;)

**Comment by azerty9971** [comment]
:'(
Maybe it's because you get both the openAPI's mQTT reports and the regular tuya's MQTT reports, I'll look into this but right now I'm in the middle of a huge refactoring to make future developments much easier and smoother :)

**Comment by BalooDK** [comment]
Great, not trying to rush you ;)
Any way to donate to you ? I really appreciate your work and support

**Comment by azerty9971** [comment]
Thanks for the offer but I'm only doing this as a hobby ;)

**Comment by BalooDK** [comment]
You do a great job. Thank you

**Comment by azerty9971** [comment]
Hello,
The new beta is out, can you test it and let me know if you still have errors?

Thanks in advance,
Azerty

**Comment by BalooDK** [comment]
I installed the beta last night, and had it running all day. Everything is a mess now 😩 None of my plugs shows the correct consumption, no matter if I use method a or b. 

1.2.7 actually worked perfectly for the last  couple of days.

**Comment by azerty9971** [comment]
Sorry about that :'(

Can you send me screenshots of the consumption history of your plugs?
Are the values too high or too low?

Again, sorry for the issue :'(

**Comment by BalooDK** [comment]
Some are way too high, some low, and some don’t show anything 

![IMG_0517](https://github.com/user-attachments/assets/8d0827a3-3bc9-476b-b051-0fdbb44997a6)
![IMG_0516](https://github.com/user-attachments/assets/0e84454f-cd6a-4037-b29b-5192fe96f06d)
![IMG_0515](https://github.com/user-attachments/assets/fcf1bb5a-2bae-408b-b0ec-4d757d735c92)
![IMG_0514](https://github.com/user-attachments/assets/2d2e2c26-baca-405a-9868-4d8145b63975)

**Comment by BalooDK** [comment]
![IMG_0519](https://github.com/user-attachments/assets/9bf4b438-3250-40ad-8c03-870f0c8c618f)
![IMG_0518](https://github.com/user-attachments/assets/ca2db8ce-983a-4441-9983-08fbeb08716c)

**Comment by azerty9971** [comment]
The state values are indeed messed up.
This will take another day to fix itself.

In the meantime, from what I see, Server should use "consumption (method B)"
(remove the other one from your dashboard)

I've figured out why this happens, I'm testing the fix for it now and will publish a release later today (hopefully)

**Comment by azerty9971** [comment]
Testing went right :)
The new beta should not copy the value of Consumption method A on initialization (thus removing these huge spikes)

Give it a day or two to see the results on both methods ;)

Have a nice day,
Azerty

**Comment by BalooDK** [comment]
Great 👍🏻 
I only put a and b in for testing ;)

**Comment by azerty9971** [comment]
Hello,
Can you test the newest version?

Also, what are the consumptions looking like after a few days?

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
Aouch, I hope you'll get better soon!!

Kind regards,
Azerty

**Comment by BalooDK** [comment]
Thank you. I do feel a lot better now, but I guess recovery will take some time.

Good thing is, everything seems to work as expected. All plugs show mostly correct consumption. Some are off 0.01 or 0.02 kW, but I can live with that.

Again, thank you for your great work
