### ISSUE TITLE
Not work after update

### ISSUE THREAD

**Issue by fraizzo** [azerty9971/xtend_tuya#39]
Hi, i just update the integration and now there is a problem. 

`Registratore: homeassistant.config_entries
Fonte: config_entries.py:586
Prima occorrenza: 19:22:43 (1 occorrenze)
Ultima registrazione: 19:22:43

Error setting up entry gg-110476445282266490383 for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 117, in async_setup_entry
    auth_type = AuthType(entry.options[CONF_AUTH_TYPE])
                         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'auth_type'`

**Comment by azerty9971** [comment]
Hello,
Please update to the latest stable release :).

This should fix it.

Let me know if it worked ;)

**Comment by fraizzo** [comment]
i update to 1.2.6 stable now but same error:

`Registratore: homeassistant.config_entries
Fonte: config_entries.py:586
Prima occorrenza: 20:23:09 (3 occorrenze)
Ultima registrazione: 20:23:51

Error setting up entry gg-110476445282266490383 for xtend_tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 121, in async_setup_entry
    auth_type = AuthType(entry.options[CONF_AUTH_TYPE])
                         ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'auth_type'`

**Comment by azerty9971** [comment]
You should be forced to ;)

But it will definitely work if you add them... (and I recommend you to do it).

Version 1.2.7 should fix this

**Comment by fraizzo** [comment]
> You should be forced to ;)
> 
> But it will definitely work if you add them... (and I recommend you to do it).
> 
> Version 1.2.7 should fix this (released just now)

GG man, it's ok now!!!!

Really thanks

**Comment by azerty9971** [comment]
Shouldn't* xD

Is it working with or without the OpenAPI credentials?

**Comment by fraizzo** [comment]
Without

Il Mer 17 Lug 2024, 20:36 azerty9971 ***@***.***> ha scritto:
