### ISSUE TITLE
intervene xtend_tuya and tuya

### ISSUE THREAD

**Issue by mplugge** [azerty9971/xtend_tuya#4]
When I use the xtend_tuya, at some point the tuya intergation no longer works. these can no longer be operated. I then have to disable the xtend_tuya app. then the tuya components work again

**Comment by azerty9971** [comment]
Hello,
This is odd, could you try restarting your home assistant next time this happens?

The only interactions between xtend and tuya is regarding the message queue listening (to prevent having the values set by xtend from being overriden by Tuya).

By any chance, does your HA often loses internet connectivity?

Have a nice day and happy holiday season!!

**Comment by mplugge** [comment]
Hi,

I have a stable internet connection 1GB fiber. is the internet connection so important for this intergation?

Of course I have started HA before :) I have more than 70 tuya components, I prefer to connect them via local_tuya for others, for example via zigbee via the tuya app. If I enable the xtend_tuya, I can no longer operate the components in tuya and local_tuya within 24 hours. then I have to restart the xtend_tuya app disable HA and then everything works again. only without the energy values. If I then enable xtend_tuya, it automatically goes wrong again after a while. The strange thing is that it does not happen immediately, but certainly within 24 hours. then I notice that the curtains do not open and other automations do not work.



Martijn

**Comment by azerty9971** [comment]
Hello,
The reason I was asking for the stability of the internet connection is that in case of a disconnection then the tuya integration could restore it in a way that interferes with the xtend_tuya integration.

Do you have entries in the log regarding either the tuya integration of the xtend_tuya integration? (Settings -> System -> Logs)

Thanks in advance for your help and best wishes :)

**Comment by mplugge** [comment]
thanks for the replay

i'm on shot hollyday, i send the files begin 2023

________________________________
Van: azerty9971 ***@***.***>
Verstuurd: vrijdag, december 29, 2023 12:31:14 p.m.
Aan: azerty9971/xtend_tuya ***@***.***>
CC: Martijn Plugge ***@***.***>; Author ***@***.***>
Onderwerp: Re: [azerty9971/xtend_tuya] intervene xtend_tuya and tuya (Issue #4)


Hello,
The reason I was asking for the stability of the internet connection is that in case of a disconnection then the tuya integration could restore it in a way that interferes with the xtend_tuya integration.

Do you have entries in the log regarding either the tuya integration of the xtend_tuya integration? (Settings -> System -> Logs)

Thanks in advance for your help and best wishes :)

**Comment by mplugge** [comment]
Hi, after my holiday I did not enter the credentials. Restarted Home Assistant a few times but everything continues to work. strange, now we don't know the cause. Thank you for responding
