### ISSUE TITLE
Trouble getting the daily consumption values even after 1.2.7. update

### ISSUE THREAD

**Issue by cperrier** [azerty9971/xtend_tuya#43]
Hello,

I was hoping that I could get correct values for the daily consumption of some of my devices, monitored by Tuya power switches, with the "new method" introduced in 1.2.7.

I see correct values in the Smart Life app but I can't get these in HA.
 
With xtend_tuya, the "consumption" sensor gives me an always increasing value which apparently is the total consumption of the device since I added it to HA. And the new "method B" sensor does indeed give a very low value which is definitely not the daily consumption.

So, I'm kinda lost in all this. Is there anyhting I could do in order to help debugging this ?

Sorry for the lack of precision in this first report, but all this is really new for me and I don't really know where to look at....but, at least I'm ready to help debugging this stuff.....

**Comment by azerty9971** [comment]
Hello,
Did you try adding the increasing sensor in the energy dashboard? That is how it's meant to be used ;)

This way you should get the correct statistics.

If the values shown in the energy dashboard are not correct then there is still more work to be done from my end :) (this will most likely apply for zwave devices, I'm working on it)

have a nice day,
Azerty

**Comment by cperrier** [comment]
Well, that might be the reason. Indeed I didn't really know that I had to add the sensor (you mean the "consumption" sensor, right?) to the energy dashboard for it to work as expected. All this is indeed a bit fuzzy for me, I have to admit...:-)

So, actually, the "consumption" (original method, back to 1.2.6) was already added to the energy dashboard and, there, it was apparently right. So, well, I might not be neededing the "method B" one. What confused me is that I tried to add a custom chart that would draw the daily consumption day by day, apart from the energy dashboard and, while such chart actually works well for other switches I'm using (Meross ones), it was not for my Tuya switches.

I'll see what happens now that I have both "consumption" sensors added to my energy dashboard (of course, it's silly to use both, but that's meant to just have a correct idea about all this.

Thanks a lot for your work, anyway, and sorry for being kind of PITA by doing things mostly by "trial and error"...;-)

Does "azerty" in you rnickname mean that you're actually French or at least french-speaking? In such case, I could mentally switch to a fr_FR locale....:-)

**Comment by azerty9971** [comment]
Hello,
Oui, je suis francophone ;) (Belge)

En effet, vous ne devriez pas avoir besoin de la méthode B, il s'agit d'une méthode pour certains appareils qui envoie la consommation totale et pas la variation de consommation.

Je ne vois pas trop ce que vous voulez dire par un graphique personnalisé, comment vous avez fait ça ?

Pas de soucis, vous n'êtes pas une PITA ;) (même si c'est délicieux ;p)

**Comment by cperrier** [comment]
Thanks for your explanations and details about this new method B. Looks like we can now close this issue.

What I was trying to do was plotting the "consumption" entity over time and what I was getting was an always increasing value, instead of a stepped value with a different value for each day. All this was....before I discover that it is indeed exactly what' is done in the Energy dashboard...:-)

Merci pour tout et amitiés de Normandie !
