### ISSUE TITLE
Reset consumption

### ISSUE THREAD

**Issue by TobiasPSP** [azerty9971/xtend_tuya#44]
I don't know if it can be done at all, but if anyone knows then it is you: is there a way to *reset* the energy consumption counter for a plug (other than resetting it completely), and if so, would it be feasible to add such functionality to your awesome integration?

I have been using it now for a few weeks, and it is amazing.

**Comment by azerty9971** [comment]
Hello,
Yes no problem, I'll add it into the next release ;)

I'll keep you posted once the feature is available.

Have a nice day,
Azerty

**Comment by TobiasPSP** [comment]
That’s awesome - very much looking forward to this!

**Comment by azerty9971** [comment]
Sorry, I forgot you in this release, I'll make this functionality available for the next beta.

Again, sorry for the waiting
Azerty

**Comment by TobiasPSP** [comment]
No prob :-) it’s great if that eventually works but not urgent. Thank you for looking into this.

**Comment by azerty9971** [comment]
Hello,
This has just been published in the new 2.0.2 version.

Enjoy!!

**Comment by TobiasPSP** [comment]
Awesome, can’t wait to test-drive! Many thanks.
