### ISSUE TITLE
Re-autenticate

### ISSUE THREAD

**Issue by fraizzo** [azerty9971/xtend_tuya#45]
Hi, today, without a reason, the integration ask to re-autenticate into account, but, after inserted the credentials not work, same error.

`Registratore: homeassistant.config_entries
Fonte: config_entries.py:586
Prima occorrenza: 14:00:00 (8 occorrenze)
Ultima registrazione: 15:10:00

Error setting up entry gg-110476445282266490383 for xtend_tuya: Authentication failed. Please re-authenticate the Tuya integration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xtend_tuya/__init__.py", line 176, in async_setup_entry
    raise ConfigEntryError(msg)
homeassistant.exceptions.ConfigEntryError: Authentication failed. Please re-authenticate the Tuya integration`

**Comment by azerty9971** [comment]
Hello,
Sometimes it takes time for the Tuya integration to show the authentication banner.

Can you try restarting HA and see if Tuya is requesting for a reauthentication?

**Comment by fraizzo** [comment]
After restart no error, but today two times same error. 

I'll check the plugin and I'll let you know

**Comment by fraizzo** [comment]
After some minute, same problem...

![Screenshot 2024-07-24 162755](https://github.com/user-attachments/assets/d9499401-1a46-4dd5-848a-7027e91c0831)

**Comment by azerty9971** [comment]
I'm finalizing a big rewrite of the whole integration, hopefully it will fix these kind of bugs ;).

The beta should come soon ;)

**Comment by fraizzo** [comment]
GG man, i'll try the new version right away

**Comment by azerty9971** [comment]
Hello,
The new beta version is out, can you please try it out and tell me if you still encounter the issue?

Thanks :)
Azerty

**Comment by azerty9971** [comment]
This should work properly now, marking as complete, if you still have the problem don't hesitate to tell me :).

Have a nice day,
Azerty
