### ISSUE TITLE
documentation to start

### ISSUE THREAD

**Issue by supermimai** [azerty9971/xtend_tuya#46]
Hello, 
as a lot of people, I miss the consumption entities in my tuya plugs and other devices , I succeed to go in deep in localtuya too to "add" some ID but for sure, I would prefer to get a more automatized solution as xtend_tuya seems to be. but the documentation isn't so obvious for a "beginner" as I considered myself.  first step ( maybe obvious or not ) but does this screenshot shows Xtend_tuya is installed and running as it supposed to be ? 

![Screenshot_2024-07-27__13_22_30](https://github.com/user-attachments/assets/51ff407b-f685-4811-875b-ff85225cd159)

I mean if 26 devices are listed in both, the detection of the devices works ?

**Comment by azerty9971** [comment]
Hello,
This seems correct indeed :).

Did the consumption entities appear in the devices when you installed Xtended Tuya?
In theory they should have...

Have a nice day,
Azerty

**Comment by supermimai** [comment]
Hello Azerty, 
so yes, indeed on some of the devices ( plugs ) , a new entities is available but not sure about how I could use it, it seems to be the total of the consumption since the start of the plug : 

![Screenshot_2024-07-28__13_10_02](https://github.com/user-attachments/assets/18fab7ea-4d52-44ca-b1aa-d9f147b9727b)
![Screenshot_2024-07-28__13_09_40](https://github.com/user-attachments/assets/2ae0ac9a-150a-497d-adfa-d9abc3b670ac)

but on some other device ( this one is a switch but with the option to follow the consumption in the smart life app ), there is no extra sensor / entities , while I was able to grab it with all the steps to add entities with local tuya hacs .

![Screenshot_2024-07-28__13_11_00](https://github.com/user-attachments/assets/baac24bd-91a7-4849-8838-f2cf50cf3a2a)

![Screenshot_2024-07-28__13_16_42](https://github.com/user-attachments/assets/22f206d8-6c97-46ae-814c-487ae3baf26c)

Do you want to support the extra device ( at least the one I succeeded to make it work also with localtuya ? ) 

thanks for all !

**Comment by azerty9971** [comment]
Hello,
The way to use the consumption entity is by adding it into the energy dashboard.
This way you'll get all the data you want (the ones like in the Tuya app)

For the device where the consumption entity is not present, can you send me the diagnostic file (the button "Download Extended Tuya diagnostic) on this screenshot:
![image](https://github.com/user-attachments/assets/a4095a54-725c-43db-88dc-a5e2de226e9c)

**Comment by supermimai** [comment]
Hello,

so here is the Diagnostic file ( for the switch "clim full" )

also a screenshot in smartlife :



let me know if you need more information :)

Regards,

Fabrice


------ Message d'origine ------
De "azerty9971" ***@***.***>
À "azerty9971/xtend_tuya" ***@***.***>
Cc "fabrice meuwissen" ***@***.***>; "Author" 
***@***.***>
Date 28/07/2024 17:59:43
Objet Re: [azerty9971/xtend_tuya] documentation to start (Issue #46)

**Comment by azerty9971** [comment]
Hello,
Did you include the diagnostic file and the screenshot?

I can't see either :/

Thanks,
Azerty

**Comment by supermimai** [comment]
Hello

Stupid me :) I replied with attachement in the email , not the web interface, here are the files again : 

[clim full tuya-e3301e5cfed188d2850ce7461eca0255-Clim full-7fff971ce635b6a5aada4cdff4fa922b.json](https://github.com/user-attachments/files/16409052/clim.full.tuya-e3301e5cfed188d2850ce7461eca0255-Clim.full-7fff971ce635b6a5aada4cdff4fa922b.json)

![451699497_1038501807944276_3693412015840307102_n](https://github.com/user-attachments/assets/9888f181-9ac1-4396-b795-d90f0f0623c7)

Hope this time it's fine ! 

For the past "Fridge" sample the problem is the unit in the energy panel, it's multiplied by a lot and don't know where to put a correction for it.   ( but I just discovered the concept of helpers to reformat the data )

**Comment by azerty9971** [comment]
Hello,
You shouldn't need any of that, just add the sensor in your energy dashboard and it should do the trick ;)

Top right : Configure energy dashboard:
![image](https://github.com/user-attachments/assets/cca5f6b0-0116-4775-9371-6ce58565e2ca)

Then add the consumption sensor in this list:
![image](https://github.com/user-attachments/assets/a4f89f37-c064-4f69-9fea-062068eeda76)

Wait a few hours and you should get all the stats you want :).

I've added for the next release the missing entities for the clim (snif, moi j'en ai pas et je meurs de chaud!) ;)

When the next release will be there, I'll ask you again for the diagnostic as there are a metric ton of new entities that should be available ;)

Have fun,
Azerty

**Comment by supermimai** [comment]
courage sans la clim :) 

I have added the frigo unit, but the scale is completely off compared to the other devices. so much , than I don't see at all the other devices ( and the "clim" should be in the top of the consumption these days ) 

![Screenshot_2024-07-29__13_17_28](https://github.com/user-attachments/assets/85b09ec7-f874-4806-b0f7-498310e303a9)

while I have the local tuya graphs which are ok ( the device is going in periods of  on / off with max 180w ) 

![Screenshot_2024-07-29__13_18_08](https://github.com/user-attachments/assets/f911a185-5529-49bb-95e6-cf9f7f10dcb7)

**Comment by azerty9971** [comment]
Hello,
The new beta version is out, can you please try it out and tell me if you still encounter the issue?
Also, could you please repost your diagnostic file after the 2.0.0 upgrade? (make sure it's the Extended Tuya diagnostic and not the regular Tuya one):
The XT one could be behind the 3 dots:
![image](https://github.com/user-attachments/assets/4d9ac3f5-0b8c-4ceb-85ef-c5b5a34568c0)

Thanks :)
Azerty

**Comment by supermimai** [comment]
Hello

thanks for your patience and work :)
here is the diagnostic , ( first time I grab it that way ) 
for this specific devices, now 3 energy values are detected but hard to see immediatly if the information are correct, at least it's installed to be tested on the day of tomorrow.

[xtend_tuya-01J3NBA10AHMJ98ZHBE668SQPC-Clim full-7fff971ce635b6a5aada4cdff4fa922b - v2 beta .json](https://github.com/user-attachments/files/16432716/xtend_tuya-01J3NBA10AHMJ98ZHBE668SQPC-Clim.full-7fff971ce635b6a5aada4cdff4fa922b.-.v2.beta.json)

the 3rd one , first I thought it was the most interesting, 
![Screenshot_2024-07-30__21_41_12](https://github.com/user-attachments/assets/9f7975f6-5a69-455d-a9fc-8ae237b8758a)
but comparing with the value of the smartlife app, it's the total_forward_energy

and the 2 others return zero for now, or "freeze" the HA history view. 

at least, I guess the diagnostic file will help you.

**Comment by azerty9971** [comment]
From what I see you don't have the cloud account configured am I correct?

Because the cloud actually gives me back the model in the diagnostic and that's really helpful to figure out what the value means...

Have a nice evening,
Azerty

**Comment by azerty9971** [comment]
Also, I forgot to put the texts, they will be there in the next release :'(

**Comment by supermimai** [comment]
well for me , the tuya cloud is configured, otherwise i wouldnt see the 3 values, but how to be sure it is ? 
another solution, I can make capture of the device in the IOT Tuya if it helps ( so back to the local tuya approach )

**Comment by azerty9971** [comment]
To check this, you can go there:
![image](https://github.com/user-attachments/assets/8334fa51-d61d-4884-a395-ffa949cbbd32)
And click the "Configure" button.

If the fields are filled in then the cloud is indeed configured.

If they are empty, you can use the following procedure to fill them in:
https://github.com/azerty9971/xtend_tuya#adding-your-tuya-cloud-credentials

Have fun,
Azerty

**Comment by supermimai** [comment]
the fields are empty .. but I can't login, whatever the option I try. And I have only 1 cloud possible in iot tuya developper.

![Screenshot_2024-07-31__15_44_47_modified](https://github.com/user-attachments/assets/a5c47f88-a77d-4eae-b4ca-72c3e412ed88)

login_error but without too much detail, I think my first tuya integration was the same the tutorial described with a qrcode.

thanks for all your effort, but I think I will survive with the methods I have already for now. maybe look in local tuya again

**Comment by azerty9971** [comment]
Can you make sure that the login used is the same as the one shown in the XT Tuya page ? (The gg -something one on my screenshot)

**Comment by supermimai** [comment]
the tuya login isn't shown, only the email ( which is the same than my smartlife account ) , and I have checked the smart life app, I see the credentials of the cloud account ( the one I use to grab the localtuya information ), I don't have any other field I can check to see if they are the same.
I just confirm the first time tuya in HA has been imported by the qrcode method.

**Comment by azerty9971** [comment]
This could happen if you didn't link your app account to the Tuya IOT cloud:
![image](https://github.com/user-attachments/assets/57363298-42fb-4c06-a94e-8fc657c1292e)
(the "Add App Account" button).

Can you verify you did these and that in the Tuya IOT cloud platform you can see the devices that are on your smartlife app?

Thanks

**Comment by azerty9971** [comment]
Also, the newest beta adds the texts that were missing to know which consumption is what ;)

**Comment by supermimai** [comment]
![Screenshot_2024-08-01__11_40_14](https://github.com/user-attachments/assets/642cf391-f6b5-489a-b7d7-8532f04cc0da)
I confirm the new beta return values, even if actually comparing with smartlife, the last one is the incremental total of consumption  from the beginning of the activation of the devices, the 2 others are flat at zero but due probably on this specific device ( a breaker which allows for airbnb for exemple to define a quota of electricity to spend ) 

![Screenshot_2024-08-01__11_40_24](https://github.com/user-attachments/assets/5689ebbd-014c-4965-858d-09a471d734df)

for the IOT / Login etc, I checked again, and it's visible from IOT Tuya account, and also from smartlife, I see the HA authorization ( for the regular tuya plugin I guess ) and the project in IOT Tuya.

I gave up and I plugged a tapo / tp link new plug to follow my fridge consumption, it's much easier than understanding how to "patch" the x1000 consumption I can see in the energy panel. ( wrong values for sure ) 

![Screenshot_2024-08-01__11_46_48](https://github.com/user-attachments/assets/a59f4e18-f48a-48ef-8880-739d9ef929da)

**Comment by azerty9971** [comment]
Hello,
Can you retest with the latest version? This should in theory be fixed :)

Enjoy!!

**Comment by supermimai** [comment]
Hello, I installed it this morning, then rebooted HA to be sure it was active. It will take me some time to check the differences, but quickly , I still have this scale value issue ( my reference plug is "frigo" as it is a daily running device max 200w , ( but I will let it a few hours to confirm ) 

thanks again for the hard work !

**Comment by azerty9971** [comment]
If it still doesn't have the correct range would it be possible for you to share the device with me so that I can investigate?

You can share it with either:
devun999999@gmail.com (tuya)
gg-106053160716494114782 (smart life)

Don't worry I won't turn the fridge off ;)

Have a nice evening,
Azerty

**Comment by supermimai** [comment]
hello, smartlife share email sent, ( I m not doing that often, so let's cross fingers it's what you expect ) 
the behavior has changed again for the reference "frigo" plug,  but as I put both a tapo ( working well for consumption ) and the tuya plug, at least to be able to compare the graphs and daily consumption. 
I have another device ( a clamp or a switch ) with a value negative in Home Assistant, and normal in the smartlife app.

**Comment by azerty9971** [comment]
Hello,
I think we fixed everything that you mentioned:).

If not feel free to reopen the issue.

Have a nice day,
Azerty

**Comment by supermimai** [comment]
no, indeed, a lot of work ( and thanks for that ) have been done, I think the version is much better and handle more devices, easier connection and I could remove the local tuya as soon as I find the way to create "today consumption"

**Comment by azerty9971** [comment]
The new sensors have been added in 2.0.6 :)
Enjoy ;)

**Comment by supermimai** [comment]
great ! I didn't know, I just forced the update and I will see and compare values from the tplink and tuya on my famous fridge reference consumption :)
I see you have even added yearly  ! it will be long term but interesting for sure
