### ISSUE TITLE
Add support for smd devices

### ISSUE THREAD

**Issue by hirocho-t** [azerty9971/xtend_tuya#53]
Hello.
I have an item called SleepChecker (Category:smd).
Can you accommodate this? Only the sensor is displayed.
I think the data_all_night property is binary data (type: raw) for creating a sleeping graph, but since I don't know the data specifications, it can be omitted.

I will send you diagnostics. (There were a lot of unnecessary devices, so I deleted some of them)

thank you.
[config_entry-xtend_tuya-50c159542874daedd046678533276557.json](https://github.com/user-attachments/files/16537081/config_entry-xtend_tuya-50c159542874daedd046678533276557.json)

**Comment by hirocho-t** [comment]
data['data']['devices']['1']['model'] has not been changed. ("model": "TZ300-2")

I forgot to mention it at the beginning, but data['data']['devices']['0'] is the device with category: wnykq, which seems to be the same as ISSUE #25.
There are no temperature and humidity sensors yet.

Thanks again!

**Comment by azerty9971** [comment]
Hello,
Can you test with the latest beta?

I see your device is an infrared device, these tend to be tricky with Tuya...

Have a nice day,
Azerty

**Comment by hirocho-t** [comment]
Hi
What I want to respond to is the smd device of the second device (data['data']['devices']['**_1_**']) in config_entry-xtend_tuya-50c159542874daedd046678533276557.json.

IR Device now displays temperature and humidity sensors.
![SmartIR_Device](https://github.com/user-attachments/assets/bed940e9-09ef-4acd-9746-9aff7e4ac16f)

**Comment by azerty9971** [comment]
Ohh, now I get it :)

I'll do that right away ;)

**Comment by azerty9971** [comment]
For the following entites, which ones are functions (things you can change from the app) and which ones are statuses (things you can only see in the app but not change):
off_bed
wakeup
off

**Comment by hirocho-t** [comment]
I don't understand English very well, but everything should be status.
It's good that you can't change it from the app.
Is this the answer?

**Comment by azerty9971** [comment]
Yes ;)
I'll post a new version in minutes ;)

**Comment by azerty9971** [comment]
New version is up, can you recheck?

**Comment by azerty9971** [comment]
If you want to test that hypothesis, open the Tuya/SmartLife app and look at the values of your device.

The values in home assistant should update at the same time as on the app...

**Comment by hirocho-t** [comment]
Not updated...
The SmartLife app on your smartphone will be updated.
DevceControl-QueryProperties in API Explorer of Tuya iot Platform is updated, but homeassistant is not updated. Does it mean that cloud_push is not performed?
![image](https://github.com/user-attachments/assets/94074de3-a213-4609-9a56-4cb9667c8439)

Also, why is "Sleep Statge" Unavailable? Either sleep or wake.
```
"sleep_stage": {
"type": "Enum",
"value": {
  "range": [
    "sleep",
    "awake"
  ]
},
```
Does the "model" mentioned at the beginning refer to this yellow part? This is helpful information about what kind of properties it has (the characters in the description are probably in Chinese)
Attach the file.
![image](https://github.com/user-attachments/assets/3c1c0efc-e795-4337-b3e7-85f1b986d159)
[Smd_QueryThingsDataModel.txt](https://github.com/user-attachments/files/16549835/Smd_QueryThingsDataModel.txt)

**Comment by azerty9971** [comment]
Yes,
the model is exactly what I need to understand what the device is giving back.

For the sleep_state, I'll check, it must be a type from my side since I did implement it...

**Comment by azerty9971** [comment]
If the cloud is updated, please follow the following instructions to add your Tuya IOT platform credentials in XT:
https://github.com/azerty9971/xtend_tuya#adding-your-tuya-cloud-credentials

I've just posted a new beta that should fix the missing entities...

**Comment by hirocho-t** [comment]
[V2.0.4-beta.4]
"sleep_stage" is good
However, even after updating XT, the credentials did not disappear. Just to be sure, I opened CONFIGURE and resubmitted, but the values ​​such as heart_beat did not change.
The reason it's not updating may be a device-specific issue.

**Comment by hirocho-t** [comment]
Hi
I tried using SleepChecker last night, but it doesn't seem to have been updated at all.
It seems that the value is updated only when HomeAssistant is restarted.

I tried outputting the debug log.
For some reason, the target device (category:smd, deviceId:585638563083988f1ee4) seems to have a value on the tuya_sharing side, which should not be supported. There seems to be no log for tuya_iot.
![image](https://github.com/user-attachments/assets/e41c0ffe-2f5e-4d51-aa4a-9dd6ff8a8df7)
[home-assistant_xtend_tuya_2024-08-09T07-17-44.454Z.log](https://github.com/user-attachments/files/16557730/home-assistant_xtend_tuya_2024-08-09T07-17-44.454Z.log)

**Comment by azerty9971** [comment]
That could be it indeed!

I'll update to prefer the Tuya Sharing side for your device type

**Comment by azerty9971** [comment]
Hello,
The latest beta should fix your issue :).

Don't hesitate to let me know if it worked :).

Have a nice day,
Azerty

**Comment by hirocho-t** [comment]
Not yet.
An error was output to the debug log.

[tuya_sharing] on message error = 'value_convert'
![image](https://github.com/user-attachments/assets/ebcfbbfb-5f01-4b7e-a98d-66b08a165847)

**Comment by azerty9971** [comment]
Hello,
The latest beta should fix the issue, can you test it out?

If it's not working we should get more debug information to figure out what is happening :).

Have a nice day,
Azerty

**Comment by hirocho-t** [comment]
The screen is not updated yet.
ERROR is gone in the log, but there is no log for the target device (category:smd, deviceId:585638563083988f1ee4).

I will provide any information you need

**Comment by azerty9971** [comment]
Hello,
I've posted a new beta, can you test it out and let me know if the values are getting updated now?

Thanks in advance,
Azerty

**Comment by hirocho-t** [comment]
I get the error "[tuya_sharing] on message error = 'statusFormat'"
[home-assistant_xtend_tuya_2024-08-11T06-10-19.327Z.log](https://github.com/user-attachments/files/16571791/home-assistant_xtend_tuya_2024-08-11T06-10-19.327Z.log)

**Comment by azerty9971** [comment]
Would it be possible for you to share temporarily this device with me so that I can investigate on my side ?

If you are using Tuya;
devun999999@gmail.com
If you are using SmartLife:
gg-106053160716494114782

To do that, you have to start the app you are using (Tuya/SmartLife), then go on the device page and share it with the correct account.

Thanks in advance,
Azerty

**Comment by hirocho-t** [comment]
Is the country Belgium?
It seems that they cannot be shared because the data centers are different.
I use the SmartLife app.
![Screenshot_2024-08-11-17-41-01-493_com tuya smartlife](https://github.com/user-attachments/assets/ebad8c42-f86b-415c-b033-bebbe9448457)
![Screenshot_2024-08-11-17-39-48-019_com tuya smartlife](https://github.com/user-attachments/assets/41d296aa-6e67-42e3-94bc-314de856e985)

**Comment by hirocho-t** [comment]
I did a little research.

Check the debug log for the error location
I found that it is line 158 of /usr/local/lib/python3.12/site-packages/tuya_sharing/manager.py.

I looked at /usr/local/lib/python3.12/site-packages/tuya_sharing/strategy.py, but I didn't understand the meaning of the source, but apparently when strategy_name is 'default',
I guessed that it was supposed to look at /usr/local/lib/python3.12/site-packages/tuya_sharing/strategy_repo/default.py.
I thought that there was no config_item["statusFormat"] in config_item in the default.py source, causing an error.
Looking at the smart plug log, it says config_item={'statusFormat': '{"cur_current":"$"}',...

Wouldn't it be better if the location where the error log appears at the end is as shown below?

before: mq _on_device_report before strategy convert strategy_name=default,dp_item=('heart_rate', 72),config_item={'valueDesc': '{"max": 150, "min": 0, "scale": 0, "step ": 1, "unit": ""}', 'valueType': <DPType.INTEGER: 'Integer'>, 'pid': 'mexpztav5vakaqp1'}
after : mq _on_device_report before strategy convert strategy_name=default,dp_item=('heart_rate', 72),config_item={**'statusFormat': '{"heart_rate":"$"}',** 'valueDesc': '{"max": 150, "min": 0, "scale": 0, "step": 1, "unit": ""}', 'valueType': <DPType.INTEGER: 'Integer'>, 'pid': 'mexpztav5vakaqp1' }

Sorry if it's completely wrong

**Comment by azerty9971** [comment]
Hello,
Sorry for the delay, I was busy this weekend.

Can you try the latest beta and let me know if it works better?

Thanks :)
Azerty

**Comment by hirocho-t** [comment]
Hello
The value has changed! wonderful!

I tried displaying the smartlife app and homeassistant app at the same time on my smartphone, but they changed to the same value at exactly the same time! amazing!
![Screenshot_2024-08-13-10-22-58-240_io homeassistant companion android__](https://github.com/user-attachments/assets/a2170c81-449a-467c-9dc6-8bd53ab56554)

thank you very much!
Thanks for the great integration!
Please close this issue.

Also, the Brightness of the wnykq device in Issue 25 can be changed, but it is just a sensor for reading.

**Comment by hirocho-t** [comment]
Hello
I will write here again without creating a new ISSUE.
It seems that V2.0.4 has been officially released.
If you update to V2.0.4, you will not be able to use smd devices or wnykq devices.
This means that all Sensors are "anavailable".
There is no problem if you roll back to v2.0.4-beta.8.
I output a debug log, but there was no smd device ID.
thank you

**Comment by azerty9971** [comment]
Hello,
I think I found the issue, can you retest please with the new release?

Thanks,
Azerty

**Comment by hirocho-t** [comment]
[V2.0.5]
It works fine.
thank you

**Comment by azerty9971** [comment]
Sorry for this, it was an error when removing some debug data :'(
