### ISSUE TITLE
question about new device discovery

### ISSUE THREAD

**Issue by supermimai** [azerty9971/xtend_tuya#75]
Hello, 
I m now running only xtend_tuya now in HA , no local_tuya, nor default tuya integration.
I have a question. I just bought ( for fun ) a plug with consumption from Action ( 8.95€ a good deal ) and I have added it by using smartlife. but what is your recommanded action ( to not mess anything ) to add this device ( or to detect it ) with xtend_tuya ? 
( it's kind of documentation request, I can follow this : 

"Enter your Smart Life or Tuya Smart user code.
You can find this code in the Smart Life app or Tuya Smart app in Settings > Account and Security screen, and enter the code shown on the User Code field. The user code is case sensitive, please be sure to enter it exactly as shown in the app."

but wasn't sure how the detection of the new device should be managed ? 

thanks by advance !

**Comment by azerty9971** [comment]
Hello,
Either restart HA or reload the XT integration (settings -> devices -> XT -> next to your username click the 3 dots -> reload configuration)

This should do the trick :)

**Comment by supermimai** [comment]
ok I will try that, but does it break / reset the daily_consumption new entity ( of existing devices ) ?

**Comment by azerty9971** [comment]
No it shouldn't :)
