### ISSUE TITLE
energy monitoring not captured with wifi smart plug

### ISSUE THREAD

**Issue by desmondyipyc** [azerty9971/xtend_tuya#78]
I am unable to capture the consumption with my wifi smart plug, on the previous version and the current version. 
Zigbee was fine with consumption before the new update that came in today and unable to to get live update of power(watts) for both version. 

Currently installed with both xtend tuya and the basic tuya integration(cloud)

**Comment by azerty9971** [comment]
that's odd, so if I understand correctly, the Power (W) is not updated anymore? (even when you are in the Tuya app?)

What version was the last that worked?

Can you post the diagnostic for the device?
In your device page, click the "Download extended tuya device diagnostics" (in the screenshot "Télécharger les diagnostics" (you might have to go to the 3 dots to have the correct diagnostics)):
![image](https://github.com/user-attachments/assets/33eb1799-d08c-4506-a33a-eab948e5d2ef)

Sorry for the inconvenience,
Azerty
