### ISSUE TITLE
daily / monthly / yearly consumption missing on 2 specific devices.

### ISSUE THREAD

**Issue by supermimai** [azerty9971/xtend_tuya#79]
Hello ! 
you know how I find the daily / montly  virtual entities are great !

but actually I have the 2 very rare devices where these entities are missing, the breaker ( the one with credits for airbnb ) and a clamp ( you should both have access to them on tuya IOT ) 

here screenshot of entities listed ( only xtended_tuya installed ) 
![Screenshot_2024-08-16__17_18_42](https://github.com/user-attachments/assets/cac96992-9a58-42fd-b5c2-f3e1ea2a63b3)
![Screenshot_2024-08-16__17_19_13](https://github.com/user-attachments/assets/033a605c-8a59-41db-a15b-b94d575dca87)

here the new fresh one ( the plug from action ) 
![Screenshot_2024-08-16__17_29_27](https://github.com/user-attachments/assets/ad0187ba-383f-4fbd-8448-9e8a6ae689d1)

**Comment by azerty9971** [comment]
Hello,
This should now be part of the latest beta.

Don't hesitate to let me know if it worked as expected :).

Have fun,
Azerty

**Comment by supermimai** [comment]
hello, I have updated and changed the values to visible, I will take a look in a few hours to see the results  ! at least it lists more "virtual" entities.

**Comment by azerty9971** [comment]
Hello,
Is everything working as expected?

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
Awesome  :D
