### ISSUE TITLE
feature request - Automatic Cat Litter Box

### ISSUE THREAD

**Issue by bierlaagh** [azerty9971/xtend_tuya#8]
I have a Tuya automatic litter box, wicht doesn't show any sensors in HA using the Tuya integration.
there are sensors available though.

` "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "31",
    "app_type": "tuyaSmart",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "Automatic Cat Litter Box",
    "model": "\u5ba0\u7269\u732b\u7802\u76c6",
    "category": "msp",
    "product_id": "5t7esmqqh92ssbe5",
    "product_name": "Automatic Cat Litter Box",
    "online": true,
    "sub": false,
    "time_zone": "+01:00",
    "active_time": "2024-01-25T11:11:32+00:00",
    "create_time": "2024-01-05T19:40:02+00:00",
    "update_time": "2024-01-25T11:11:34+00:00",
    "function": {
      "deodorization": {
        "type": "Boolean",
        "value": {}
      }
    },
    "status_range": {
      "cat_weight": {
        "type": "Integer",
        "value": {
          "unit": "g",
          "min": 600,
          "max": 10000,
          "scale": 0,
          "step": 1
        }
      },
      "excretion_times_day": {
        "type": "Integer",
        "value": {
          "unit": "times",
          "min": 0,
          "max": 60,
          "scale": 0,
          "step": 1
        }
      },
      "excretion_time_day": {
        "type": "Integer",
        "value": {
          "unit": "s",
          "min": 0,
          "max": 1800,
          "scale": 0,
          "step": 1
        }
      },
      "deodorization": {
        "type": "Boolean",
        "value": {}
      },
      "fault": {
        "type": "Bitmap",
        "value": {
          "label": [
            "motor_fault",
            "program_fault",
            "g_sensor_fault"
          ],
          "maxlen": 3
        }
      }
    },
    "status": {
      "cat_weight": 1357,
      "excretion_times_day": 1,
      "excretion_time_day": 98,
      "deodorization": false,
      "fault": 0
    },
    "home_assistant": {
      "name": "Automatic Cat Litter Box",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    }
  }
}`

which i pulled from the download diagnostic.
I would love to fork this repro and add is myself, but no clue where to start.
therefor this feature request.

the ID I know they exist:
Sensor:
6: Weight
8: Excretion Time

Number:
117: Clumping Time (min: 0, max: 60)
118: Cleaning Interval (min: 0, max: 120)
127: Detection Sensitivity (min: 600, max: 1500, increment: 100)
124: Waste Bin Calibration (min: 0, max : 15)
125: Litter level setting: (min: 0, max: 6)

Switch:
101: Clean
102: Empty
105: Auto
111: IR-sensor
114: Child lock
122: Do not disturb
120: Odourless

Binary sensor:
119: Full

**Comment by azerty9971** [comment]
Can you contact me via e-mail on devun999999 at gmail.com? We'll plan a call and we'll try to figure these out together ;)

**Comment by bierlaagh** [comment]
I did. Hope you received the email

**Comment by azerty9971** [comment]
This has been merged in the latest version.

Have a nice evening,
Azerty
