### ISSUE TITLE
unaccurate daily consumption B for ZIGBEE plug

### ISSUE THREAD

**Issue by desmondyipyc** [azerty9971/xtend_tuya#82]
Consumption B is working 
![image](https://github.com/user-attachments/assets/2d522e58-aaaf-4224-9dd0-e68894d2b51a)

However, daily consumption B will reflect the current overall when there is an increase in kwh
Below image show that it is being reset but it jump back up to current overall
![image](https://github.com/user-attachments/assets/88079f8d-a5aa-44a4-8edf-d5d851b12fd1)

diagnotic file
https://pastecode.io/s/qc0ddxks

**Comment by azerty9971** [comment]
Hello,
The latest beta should fix the issue.

Sorry for the inconvenience,
Azerty

**Comment by desmondyipyc** [comment]
Am on 2.0.7 beta 3 now, it is fixed, thank you for your hardwork!
