### ISSUE TITLE
koyqwqf7ym95uria Missing entities

### ISSUE THREAD

**Issue by lupinve** [azerty9971/xtend_tuya#87]
For me doesn't work
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.8.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.6.44-haos",
    "supervisor": "2024.08.0",
    "host_os": "Home Assistant OS 13.0",
    "docker_version": "26.1.4",
    "chassis": "vm",
    "run_as_root": true
  },
     },
    "xtend_tuya": {
      "documentation": "https://github.com/azerty9971/xtend_tuya",
      "version": "2.0.7",
      "requirements": [
        "tuya-device-sharing-sdk==0.1.9",
        "tuya-iot-py-sdk==0.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "codeowners": [
      "Tuya",
      "zlinoliver",
      "frenck"
    ],
    "config_flow": true,
    "dependencies": [
      "ffmpeg"
    ],
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "loggers": [
      "tuya_iot"
    ],
    "requirements": [
      "tuya-device-sharing-sdk==0.1.9"
    ],
    "is_built_in": true
  },
  "setup_times": {
    "null": {
      "setup": 3.151199780404568e-05
    },
    "01J5RTYCMR3GSV1GVCQGJT43CY": {
      "wait_import_platforms": -1.3691756000043824,
      "wait_base_component": -0.008522749005351216,
      "config_entry_setup": 2.7115296390256844
    }
  },
  "data": {
    "endpoint": "https://apigw.tuyaeu.com",
    "terminal_id": "1724226162721bbwJHu",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "***********************",
    "name": "Pdc",
    "category": "aqcz",
    "product_id": "koyqwqf7ym95uria",
    "product_name": "wifi\u667a\u80fd\u7535\u8868",
    "online": true,
    "sub": false,
    "time_zone": "+02:00",
    "active_time": "2024-08-20T18:14:26+00:00",
    "create_time": "2024-08-20T18:14:26+00:00",
    "update_time": "2024-08-20T18:14:26+00:00",
    "function": {},
    "status_range": {},
    "status": {},
    "home_assistant": {
      "name": "Pdc",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": []
    },
    "set_up": false,
    "support_local": true

**Comment by azerty9971** [comment]
Hello,
Did you configure your Tuya cloud credentials? (https://github.com/azerty9971/xtend_tuya#adding-your-tuya-cloud-credentials)

Because from your diagnostic file it seems that your device is not reporting anything :'(.

**Comment by lupinve** [comment]
Hi,

Thanks for your help.

Yes, I have configured my Tuya credential

[image: Immagine 2024-08-21 115818.jpg]

Il giorno mer 21 ago 2024 alle ore 11:51 azerty9971 <
***@***.***> ha scritto:

**Comment by azerty9971** [comment]
and did you reload the integration or restart home assistant after doing that?

**Comment by lupinve** [comment]
Yes, I restarted Home Assistant

Il giorno mer 21 ago 2024 alle ore 12:08 azerty9971 <
***@***.***> ha scritto:

**Comment by azerty9971** [comment]
Hmm,
I'd need to investigate this further...

Would you be able to share the device with me?
(Don't worry, I won't turn it off).

To do that, open your Tuya/Smartlife app, click the device, then you'll have a share option.
Depending on the app you use, the account to share it with is different:
Smartlife: gg-106053160716494114782
Tuya: devun999999@gmail.com

Sorry for the inconvenience,
Azerty

**Comment by lupinve** [comment]
Yes, i share it with   ***@***.***

Thank you

Il giorno mer 21 ago 2024 alle ore 12:31 azerty9971 <
***@***.***> ha scritto:

**Comment by lupinve** [comment]
Hi,

new it works :)

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.8.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.6.44-haos",
    "supervisor": "2024.08.0",
    "host_os": "Home Assistant OS 13.0",
    "docker_version": "26.1.4",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "localtuya": {
      "documentation": "https://github.com/rospogrigio/localtuya/",
      "version": "5.2.1",
      "requirements": []
    },
    "alarmo": {
      "documentation": "https://github.com/nielsfaber/alarmo",
      "version": "v1.10.4",
      "requirements": []
    },
    "irrigation_unlimited": {
      "documentation": "https://github.com/rgc99/irrigation_unlimited",
      "version": "2024.8.0",
      "requirements": [
        "crontab"
      ]
    },
    "smartir": {
      "documentation": "https://github.com/smartHomeHub/SmartIR",
      "version": "1.17.9",
      "requirements": [
        "aiofiles>=0.6.0"
      ]
    },
    "sun2": {
      "documentation": "
https://github.com/pnbruckner/ha-sun2/blob/3.3.3/README.md",
      "version": "3.3.3",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "tapo": {
      "documentation": "
https://github.com/petretiandrea/home-assistant-tapo-p100",
      "version": "3.1.2",
      "requirements": [
        "plugp100==5.1.3"
      ]
    },
    "spotcast": {
      "documentation": "https://github.com/fondberg/spotcast",
      "version": "v3.8.0",
      "requirements": []
    },
    "smartthinq_sensors": {
      "documentation": "https://github.com/ollo69/ha-smartthinq-sensors",
      "version": "0.39.2",
      "requirements": [
        "pycountry>=23.12.11",
        "xmltodict>=0.13.0",
        "charset_normalizer>=3.2.0"
      ]
    },
    "lovelace_gen": {
      "documentation": "",
      "version": "0.1.2",
      "requirements": [
        "jinja2"
      ]
    },
    "huawei_solar": {
      "documentation": "https://github.com/wlcrs/huawei_solar/wiki",
      "version": "1.4.1",
      "requirements": [
        "huawei-solar==2.3.0"
      ]
    },
    "vimar": {
      "documentation": "https://github.com/h4de5/home-assistant-vimar",
      "version": "2023.8.0",
      "requirements": []
    },
    "frigate": {
      "documentation": "https://github.com/blakeblackshear/frigate",
      "version": "5.3.0",
      "requirements": [
        "pytz"
      ]
    },
    "reolink_dev": {
      "documentation": "https://github.com/fwestenberg/reolink_dev",
      "version": "0.64",
      "requirements": [
        "reolink==0.0.64",
        "aiosmtpd>=1.4.2"
      ]
    },
    "browser_mod": {
      "documentation": "
https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.3.1",
      "requirements": []
    },
    "xtend_tuya": {
      "documentation": "https://github.com/azerty9971/xtend_tuya",
      "version": "2.0.7",
      "requirements": [
        "tuya-device-sharing-sdk==0.1.9",
        "tuya-iot-py-sdk==0.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "codeowners": [
      "Tuya",
      "zlinoliver",
      "frenck"
    ],
    "config_flow": true,
    "dependencies": [
      "ffmpeg"
    ],
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "loggers": [
      "tuya_iot"
    ],
    "requirements": [
      "tuya-device-sharing-sdk==0.1.9"
    ],
    "is_built_in": true
  },
  "setup_times": {
    "null": {
      "setup": 3.1610019505023956e-05
    },
    "01J5SY6M74N1QRFQ65YGTRRF13": {
      "wait_import_platforms": -2.487417528987862,
      "wait_base_component": -0.002428677980788052,
      "config_entry_setup": 4.136410844977945
    }
  },
  "data": {
    "endpoint": "https://apigw.tuyaeu.com",
    "terminal_id": "1724226162721bbwJHu",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "xxxxxxxxxxxxxx",
    "name": "Pdc",
    "category": "aqcz",
    "product_id": "koyqwqf7ym95uria",
    "product_name": "wifi\u667a\u80fd\u7535\u8868",
    "online": true,
    "sub": false,
    "time_zone": "+02:00",
    "active_time": "2024-08-20T18:14:26+00:00",
    "create_time": "2024-08-20T18:14:26+00:00",
    "update_time": "2024-08-20T18:14:26+00:00",
    "function": {},
    "status_range": {
      "add_ele": {
        "type": "Integer",
        "value": {
          "max": 50000,
          "min": 0,
          "scale": 3,
          "step": 100,
          "unit": "kW\u00b7h"
        }
      },
      "cur_current": {
        "type": "Integer",
        "value": {
          "max": 30000,
          "min": 0,
          "scale": 0,
          "step": 1,
          "unit": "mA"
        }
      },
      "cur_power": {
        "type": "Integer",
        "value": {
          "max": 80000,
          "min": 0,
          "scale": 1,
          "step": 1,
          "unit": "W"
        }
      },
      "cur_voltage": {
        "type": "Integer",
        "value": {
          "max": 5000,
          "min": 0,
          "scale": 1,
          "step": 1,
          "unit": "V"
        }
      },
      "test_bit": {
        "type": "Integer",
        "value": {
          "max": 5,
          "min": 0,
          "scale": 0,
          "step": 1
        }
      },
      "voltage_coe": {
        "type": "Integer",
        "value": {
          "max": 1000000,
          "min": 0,
          "scale": 0,
          "step": 1
        }
      },
      "electric_coe": {
        "type": "Integer",
        "value": {
          "max": 1000000,
          "min": 0,
          "scale": 0,
          "step": 1
        }
      },
      "power_coe": {
        "type": "Integer",
        "value": {
          "max": 1000000,
          "min": 0,
          "scale": 0,
          "step": 1
        }
      },
      "electricity_coe": {
        "type": "Integer",
        "value": {
          "max": 1000000,
          "min": 0,
          "scale": 0,
          "step": 1
        }
      },
      "fault": {
        "type": "Raw",
        "value": {
          "label": [
            "ov_cr",
            "ov_vol",
            "ov_pwr",
            "ls_cr",
            "ls_vol",
            "ls_pow"
          ],
          "maxlen": 6
        }
      },
      "power_reactive": {
        "type": "Integer",
        "value": {
          "max": 100,
          "min": 30,
          "scale": 1,
          "step": 1,
          "unit": "W"
        }
      },
      "power_effective": {
        "type": "Integer",
        "value": {
          "max": 200000,
          "min": 10,
          "scale": 1,
          "step": 1,
          "unit": "W"
        }
      },
      "add_ele2": {
        "type": "Integer",
        "value": {
          "max": 50000,
          "min": 0,
          "scale": 3,
          "step": 100,
          "unit": "kW\u00b7h"
        }
      },
      "add_ele_today": {
        "type": "Integer",
        "value": {
          "max": 50000,
          "min": 0,
          "scale": 3,
          "step": 100,
          "unit": "kW\u00b7h"
        }
      },
      "add_ele_this_month": {
        "type": "Integer",
        "value": {
          "max": 50000,
          "min": 0,
          "scale": 3,
          "step": 100,
          "unit": "kW\u00b7h"
        }
      },
      "add_ele_this_year": {
        "type": "Integer",
        "value": {
          "max": 50000,
          "min": 0,
          "scale": 3,
          "step": 100,
          "unit": "kW\u00b7h"
        }
      },
      "add_ele2_today": {
        "type": "Integer",
        "value": {
          "max": 50000,
          "min": 0,
          "scale": 3,
          "step": 100,
          "unit": "kW\u00b7h"
        }
      },
      "add_ele2_this_month": {
        "type": "Integer",
        "value": {
          "max": 50000,
          "min": 0,
          "scale": 3,
          "step": 100,
          "unit": "kW\u00b7h"
        }
      },
      "add_ele2_this_year": {
        "type": "Integer",
        "value": {
          "max": 50000,
          "min": 0,
          "scale": 3,
          "step": 100,
          "unit": "kW\u00b7h"
        }
      }
    },
    "status": {
      "add_ele": 10,
      "cur_current": 446,
      "cur_power": 98,
      "cur_voltage": 2426,
      "test_bit": 0,
      "voltage_coe": 0,
      "electric_coe": 0,
      "power_coe": 0,
      "electricity_coe": 0,
      "fault": 0,
      "power_reactive": 50,
      "power_effective": 40000,
      "add_ele2": 10,
      "add_ele_today": 10,
      "add_ele_this_month": 10,
      "add_ele_this_year": 10,
      "add_ele2_today": 0,
      "add_ele2_this_month": 0,
      "add_ele2_this_year": 0
    },
    "home_assistant": {
      "name": "Pdc",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": true,
          "disabled_by": "integration",
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "kWh",
          "state": null
        },
        {
          "disabled": true,
          "disabled_by": "integration",
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "kWh",
          "state": null
        },
        {
          "disabled": true,
          "disabled_by": "integration",
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "kWh",
          "state": null
        },
        {
          "disabled": true,
          "disabled_by": "integration",
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "kWh",
          "state": null
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "button.pdc_reset_consumption",
            "state": "unknown",
            "attributes": {
              "friendly_name": "Pdc Reset consumption"
            },
            "last_changed": "2024-08-21T11:56:24.927446+00:00",
            "last_reported": "2024-08-21T11:56:24.927446+00:00",
            "last_updated": "2024-08-21T11:56:24.927446+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "kWh",
          "state": {
            "entity_id": "sensor.pdc_consumption",
            "state": "0.01",
            "attributes": {
              "state_class": "total_increasing",
              "unit_of_measurement": "kWh",
              "device_class": "energy",
              "friendly_name": "Pdc Consumption"
            },
            "last_changed": "2024-08-21T11:56:24.933824+00:00",
            "last_reported": "2024-08-21T11:56:24.933824+00:00",
            "last_updated": "2024-08-21T11:56:24.933824+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "kWh",
          "state": {
            "entity_id": "sensor.pdc_daily_consumption",
            "state": "0.01",
            "attributes": {
              "state_class": "total_increasing",
              "unit_of_measurement": "kWh",
              "device_class": "energy",
              "friendly_name": "Pdc Daily consumption"
            },
            "last_changed": "2024-08-21T11:56:24.934991+00:00",
            "last_reported": "2024-08-21T11:56:24.934991+00:00",
            "last_updated": "2024-08-21T11:56:24.934991+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "kWh",
          "state": {
            "entity_id": "sensor.pdc_monthly_consumption",
            "state": "0.01",
            "attributes": {
              "state_class": "total_increasing",
              "unit_of_measurement": "kWh",
              "device_class": "energy",
              "friendly_name": "Pdc Monthly consumption"
            },
            "last_changed": "2024-08-21T11:56:24.935668+00:00",
            "last_reported": "2024-08-21T11:56:24.935668+00:00",
            "last_updated": "2024-08-21T11:56:24.935668+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "energy",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "kWh",
          "state": {
            "entity_id": "sensor.pdc_yearly_consumption",
            "state": "0.01",
            "attributes": {
              "state_class": "total_increasing",
              "unit_of_measurement": "kWh",
              "device_class": "energy",
              "friendly_name": "Pdc Yearly consumption"
            },
            "last_changed": "2024-08-21T11:56:24.936716+00:00",
            "last_reported": "2024-08-21T11:56:24.936716+00:00",
            "last_updated": "2024-08-21T11:56:24.936716+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "W",
          "state": {
            "entity_id": "sensor.pdc_power",
            "state": "9.8",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "W",
              "device_class": "power",
              "friendly_name": "Pdc Power"
            },
            "last_changed": "2024-08-21T11:58:57.750654+00:00",
            "last_reported": "2024-08-21T11:58:57.750654+00:00",
            "last_updated": "2024-08-21T11:58:57.750654+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true
  }

Il giorno mer 21 ago 2024 alle ore 12:44 Matteo Marcuglia ***@***.***>
ha scritto:

**Comment by azerty9971** [comment]
But do you have the values that are getting updated?

Because on my side it did indeed show the entities, but they were not updated...

**Comment by lupinve** [comment]
Yes, they are updating. I was testing the Local Tuya integration, and
after restarting again, I started seeing the entities from your
integration.[image:
Immagine 2024-08-21 141000.jpg]



Il giorno mer 21 ago 2024 alle ore 14:04 azerty9971 <
***@***.***> ha scritto:

**Comment by azerty9971** [comment]
Nice, then it's most likely an issue with the sharing itself on my side :).

Glad that it works ;)

You can unshare the device if you will ;)

Have a nice day,
Azerty

**Comment by lupinve** [comment]
Ok
Thank you

Il giorno mer 21 ago 2024 alle ore 14:16 azerty9971 <
***@***.***> ha scritto:
