### ISSUE TITLE
Kw unit x1000 for a plug ( regression ) 

### ISSUE THREAD

**Issue by supermimai** [azerty9971/xtend_tuya#98]
Hello

sorry to bother you but with one of the recent release, the unit calculation is wrong like in the old version v2. it's my "fridge plug" than you know which show again a value 1000x higher than it should.

let me know if you want the log or if somebody else reported the issue.

thanks, 

Fabrice, France

**Comment by azerty9971** [comment]
Hello Fabrice,
By any chance is it this one? (I have way too many devices on my install xD)

![image](https://github.com/user-attachments/assets/6d02fb6e-9ae4-432b-bbf7-420f19413ae7)

If it is, then on my side it works like it should, are you using XT alongside Tuya? Do you have cloud credentials configured? Are by any chance the cloud credentials expired?

Thanks for your input :).
Azerty

**Comment by supermimai** [comment]
Hello

I just login again into Cloud IOT Tuya, I just accepted the new agreement, but I still see the project.
I m not using the regular Tuya integration anymore. 
yes, if it is the ID of the plug / entity, from my home assistant I see this ID too : wifvoilfrqeo6hvu

for checking deeply the credentials status ( expired ) I m not sure how to do it.

thanks, 

Fabrice

**Comment by azerty9971** [comment]
https://meet.google.com/ord-ipru-doy

;)

**Comment by supermimai** [comment]
sorry I can't now, I am about to leave for the rest of the day :(

**Comment by azerty9971** [comment]
no worries, shoot me an email when you can ;)

**Comment by supermimai** [comment]
I can be online tonight or tomorrow evening, I have installed the beta 9 
also, the topic seems to be discussed here too : 
https://www.facebook.com/groups/2091834914421201/user/705775293/

**Comment by azerty9971** [comment]
I'm available as from now :).
What time would work for you? (you can post a google meet meeting here and I'll join ASAP ;)).

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
This issue was because of expired cloud credentials, if you have the same one, go to the Tuya IOT Platform, log in, then go to "Cloud" -> "Services", next to the "Alerting" line, click view detail and extend your trial period for another 6 months.
