### ISSUE TITLE
Missing "humidity" on temp sens

### ISSUE THREAD

**Issue by fraizzo** [azerty9971/xtend_tuya#99]
Hi, after last update i miss "humidity" on all my temp sens, on the app all is ok

**Comment by azerty9971** [comment]
Hello,
Can you provide the diagnostics of the device?

Also, in the system logs (Settings -> System -> Logs) do you see any error?

Thanks in advance,
Azerty

**Comment by fraizzo** [comment]
No error on logs...

![image](https://github.com/user-attachments/assets/c77b94a8-dae7-44ff-9bcc-7c96bdb8057d)

**Comment by azerty9971** [comment]
Can you post me the diagnostics of the device?
the "Download diagnostics" in the following screenshot:
![image](https://github.com/user-attachments/assets/fd8d81f1-73a8-46de-8750-e2a42bf58ac2)

**Comment by fraizzo** [comment]
`"home_assistant": {
      "name": "Sensore Paolo",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "sensor.sensore_paolo_temperature",
            "state": "22.1",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "friendly_name": "Sensore Paolo Temperatura"
            },
            "last_changed": "2024-09-17T13:06:44.971949+00:00",
            "last_reported": "2024-09-17T13:06:45.478057+00:00",
            "last_updated": "2024-09-17T13:06:44.971949+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "humidity",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.sensore_paolo_humidity",
            "state": "unavailable",
            "attributes": {
              "restored": true,
              "state_class": "measurement",
              "device_class": "humidity",
              "friendly_name": "Humidity",
              "supported_features": 0,
              "unit_of_measurement": "%"
            },
            "last_changed": "2024-09-17T06:21:57.697279+00:00",
            "last_reported": "2024-09-17T06:21:57.697279+00:00",
            "last_updated": "2024-09-17T06:21:57.697279+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.sensore_paolo_battery_state",
            "state": "middle",
            "attributes": {
              "friendly_name": "Sensore Paolo Stato della batteria"
            },
            "last_changed": "2024-09-17T13:06:45.478106+00:00",
            "last_reported": "2024-09-17T13:06:45.478106+00:00",
            "last_updated": "2024-09-17T13:06:45.478106+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true,
    "data_model": ""
`

**Comment by fraizzo** [comment]
"home_assistant": {
      "name": "Sensore Paolo",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "sensor.sensore_paolo_temperature",
            "state": "22.1",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "friendly_name": "Sensore Paolo Temperatura"
            },
            "last_changed": "2024-09-17T13:06:44.971949+00:00",
            "last_reported": "2024-09-17T13:06:45.478057+00:00",
            "last_updated": "2024-09-17T13:06:44.971949+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "humidity",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.sensore_paolo_humidity",
            "state": "unavailable",
            "attributes": {
              "restored": true,
              "state_class": "measurement",
              "device_class": "humidity",
              "friendly_name": "Humidity",
              "supported_features": 0,
              "unit_of_measurement": "%"
            },
            "last_changed": "2024-09-17T06:21:57.697279+00:00",
            "last_reported": "2024-09-17T06:21:57.697279+00:00",
            "last_updated": "2024-09-17T06:21:57.697279+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.sensore_paolo_battery_state",
            "state": "middle",
            "attributes": {
              "friendly_name": "Sensore Paolo Stato della batteria"
            },
            "last_changed": "2024-09-17T13:06:45.478106+00:00",
            "last_reported": "2024-09-17T13:06:45.478106+00:00",
            "last_updated": "2024-09-17T13:06:45.478106+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true,
    "data_model": ""

**Comment by azerty9971** [comment]
This can't be complete (otherwise there is something seriously wrong with your HA).

Can you post the full diagnostic file please? (you can drop it in the comment on github...)

Thanks,
Azerty

**Comment by fraizzo** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.9.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Rome",
    "os_name": "Linux",
    "os_version": "6.6.46-haos",
    "supervisor": "2024.09.1",
    "host_os": "Home Assistant OS 13.1",
    "docker_version": "26.1.4",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "webrtc": {
      "documentation": "https://github.com/AlexxIT/WebRTC",
      "version": "v3.5.2",
      "requirements": []
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "better_thermostat": {
      "documentation": "https://github.com/KartoffelToby/better_thermostat",
      "version": "1.6.0",
      "requirements": []
    },
    "browser_mod": {
      "documentation": "https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.3.1",
      "requirements": []
    },
    "bodymiscale": {
      "documentation": "https://github.com/dckiller51/bodymiscale",
      "version": "2024.6.0",
      "requirements": [
        "cachetools==5.3.0"
      ]
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.8.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "sagemcom_fast": {
      "documentation": "https://github.com/imicknl/ha-sagemcom-fast",
      "version": "0.3.5",
      "requirements": [
        "sagemcom_api==1.3.2"
      ]
    },
    "bambu_lab": {
      "documentation": "https://github.com/greghesp/ha-bambulab",
      "version": "2.0.22",
      "requirements": []
    },
    "icloud3": {
      "documentation": "https://gcobb321.github.io/icloud3_v3_docs/#/",
      "version": "3.0.5.8",
      "requirements": []
    },
    "elkbledom": {
      "documentation": "https://github.com/dave-code-ruiz/elkbledom",
      "version": "1.0.2",
      "requirements": [
        "bleak-retry-connector>=1.17.1",
        "bleak>=0.17.0"
      ]
    },
    "xtend_tuya": {
      "documentation": "https://github.com/azerty9971/xtend_tuya",
      "version": "3.0.0",
      "requirements": [
        "tuya-device-sharing-sdk==0.1.9",
        "tuya-iot-py-sdk==0.6.6"
      ]
    },
    "dreame_vacuum": {
      "documentation": "https://github.com/Tasshack/dreame-vacuum",
      "version": "v2.0.0b16",
      "requirements": [
        "pillow",
        "numpy",
        "pybase64",
        "requests",
        "pycryptodome",
        "python-miio",
        "py-mini-racer",
        "paho-mqtt"
      ]
    },
    "smartir": {
      "documentation": "https://github.com/smartHomeHub/SmartIR",
      "version": "1.17.9",
      "requirements": [
        "aiofiles>=0.6.0"
      ]
    },
    "hass_agent": {
      "documentation": "https://github.com/LAB02-Research/HASS.Agent-Integration",
      "version": "2022.11.9",
      "requirements": []
    },
    "hon": {
      "documentation": "https://github.com/Andre0512/hon/",
      "version": "0.14.0",
      "requirements": [
        "pyhOn==0.17.5"
      ]
    },
    "xiaomi_miot": {
      "documentation": "https://github.com/al-one/hass-xiaomi-miot",
      "version": "0.7.20",
      "requirements": [
        "construct>=2.10.68",
        "python-miio>=0.5.12",
        "micloud>=0.5"
      ]
    }
  },
  "integration_manifest": {
    "domain": "xtend_tuya",
    "name": "Xtended Tuya",
    "after_dependencies": [
      "tuya"
    ],
    "codeowners": [
      "azerty9971"
    ],
    "config_flow": true,
    "dependencies": [
      "ffmpeg",
      "http"
    ],
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "documentation": "https://github.com/azerty9971/xtend_tuya",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/azerty9971/xtend_tuya/issues",
    "loggers": [
      "tuya_iot",
      "tuya_sharing"
    ],
    "requirements": [
      "tuya-device-sharing-sdk==0.1.9",
      "tuya-iot-py-sdk==0.6.6"
    ],
    "version": "3.0.0",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 2.5929068215191364e-05
    },
    "01J4Y6AG23WQY3TFWDB8PSREC9": {
      "wait_import_platforms": -0.029575510998256505,
      "wait_base_component": -0.0005840379744768143,
      "config_entry_setup": 2.0032093729823828
    }
  },
  "data": {
    "mqtt_connected": null,
    "disabled_by": null,
    "disabled_polling": false,
    "id": "bf203bb382a637d1693yye",
    "name": "Sensore Paolo",
    "category": "wsdcg",
    "local_key": "r|`YJk~8A60EV$l$",
    "product_id": "lf36y5nwb8jkxwgg",
    "product_name": "T & H Sensor",
    "online": true,
    "sub": false,
    "time_zone": "+02:00",
    "active_time": "2024-07-26T10:36:29+00:00",
    "create_time": "2024-07-26T10:36:29+00:00",
    "update_time": "2024-07-26T10:36:29+00:00",
    "function": {
      "temp_unit_convert": {
        "type": "Enum",
        "value": {
          "range": [
            "c",
            "f"
          ]
        },
        "property_update": false
      }
    },
    "status_range": {
      "va_temperature": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": -200,
          "max": 600,
          "scale": 1,
          "step": 1
        },
        "property_update": false
      },
      "va_humidity": {
        "type": "Integer",
        "value": {
          "unit": "%",
          "min": 0,
          "max": 99,
          "scale": 0,
          "step": 1
        },
        "property_update": false
      },
      "battery_state": {
        "type": "Enum",
        "value": {
          "range": [
            "low",
            "middle",
            "high"
          ]
        },
        "property_update": false
      },
      "temp_unit_convert": {
        "type": "Enum",
        "value": {
          "range": [
            "c",
            "f"
          ]
        },
        "property_update": false
      }
    },
    "status": {
      "va_temperature": 221,
      "battery_state": "middle",
      "temp_unit_convert": "c",
      "va_humidity": 57
    },
    "local_strategy": {
      "1": {
        "value_convert": "default",
        "status_code": "va_temperature",
        "config_item": {
          "statusFormat": "{\"va_temperature\":\"$\"}",
          "valueDesc": "{\"unit\":\"\u2103\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "lf36y5nwb8jkxwgg"
        },
        "status_code_alias": []
      },
      "2": {
        "value_convert": "default",
        "status_code": "humidity_value",
        "config_item": {
          "statusFormat": "{\"va_humidity\":\"$\"}",
          "valueDesc": "{\"unit\":\"%\",\"min\":0,\"max\":99,\"scale\":0,\"step\":1}",
          "valueType": "Integer",
          "enumMappingMap": {},
          "pid": "lf36y5nwb8jkxwgg"
        },
        "status_code_alias": [
          "va_humidity"
        ]
      },
      "3": {
        "value_convert": "default",
        "status_code": "battery_state",
        "config_item": {
          "statusFormat": "{\"battery_state\":\"$\"}",
          "valueDesc": "{\"range\":[\"low\",\"middle\",\"high\"]}",
          "valueType": "Enum",
          "enumMappingMap": {},
          "pid": "lf36y5nwb8jkxwgg"
        },
        "status_code_alias": []
      },
      "9": {
        "value_convert": "default",
        "status_code": "temp_unit_convert",
        "config_item": {
          "statusFormat": "{\"temp_unit_convert\":\"$\"}",
          "valueDesc": "{\"range\":[\"c\",\"f\"]}",
          "valueType": "Enum",
          "enumMappingMap": {},
          "pid": "lf36y5nwb8jkxwgg"
        },
        "status_code_alias": []
      }
    },
    "home_assistant": {
      "name": "Sensore Paolo",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "temperature",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "\u00b0C",
          "state": {
            "entity_id": "sensor.sensore_paolo_temperature",
            "state": "22.1",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "\u00b0C",
              "device_class": "temperature",
              "friendly_name": "Sensore Paolo Temperatura"
            },
            "last_changed": "2024-09-17T13:06:44.971949+00:00",
            "last_reported": "2024-09-17T13:06:45.478057+00:00",
            "last_updated": "2024-09-17T13:06:44.971949+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": "humidity",
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.sensore_paolo_humidity",
            "state": "unavailable",
            "attributes": {
              "restored": true,
              "state_class": "measurement",
              "device_class": "humidity",
              "friendly_name": "Humidity",
              "supported_features": 0,
              "unit_of_measurement": "%"
            },
            "last_changed": "2024-09-17T06:21:57.697279+00:00",
            "last_reported": "2024-09-17T06:21:57.697279+00:00",
            "last_updated": "2024-09-17T06:21:57.697279+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "sensor.sensore_paolo_battery_state",
            "state": "middle",
            "attributes": {
              "friendly_name": "Sensore Paolo Stato della batteria"
            },
            "last_changed": "2024-09-17T13:06:45.478106+00:00",
            "last_reported": "2024-09-17T13:06:45.478106+00:00",
            "last_updated": "2024-09-17T13:06:45.478106+00:00"
          }
        }
      ]
    },
    "set_up": true,
    "support_local": true,
    "data_model": ""
  }
}

**Comment by fraizzo** [comment]
[xtend_tuya-01J4Y6AG23WQY3TFWDB8PSREC9-Sensore Paolo-0a9c0928f5d9bbe820ab5e99c405f75a.json](https://github.com/user-attachments/files/17029209/xtend_tuya-01J4Y6AG23WQY3TFWDB8PSREC9-Sensore.Paolo-0a9c0928f5d9bbe820ab5e99c405f75a.json)

**Comment by azerty9971** [comment]
That is very odd, it should work...

I'm guessing you're using both Tuya and Xtend Tuya? if so, can you try disabling Tuya?

**Comment by azerty9971** [comment]
(and restart Home Assistant after doing so :) )

**Comment by fraizzo** [comment]
i'm not using both, i removed tuya long time ago

**Comment by fraizzo** [comment]
[home-assistant_2024-09-18T10-32-14.596Z.log](https://github.com/user-attachments/files/17042557/home-assistant_2024-09-18T10-32-14.596Z.log)

**Comment by azerty9971** [comment]
Hello,
The information returned was all valid, I've added some other debug information to the latest BETA build, can you update to 3.0.0-beta.9 and re-export the system logs please?

Thanks,
Azerty

**Comment by fraizzo** [comment]
[home-assistant_2024-09-18T10-32-14.596Z.log](https://github.com/user-attachments/files/17043327/home-assistant_2024-09-18T10-32-14.596Z.log)

done

**Comment by azerty9971** [comment]
I think you reuploaded the same file :/

**Comment by fraizzo** [comment]
[Uploading home-assistant_2024-09-19T09-22-27.605Z.log…]()

sorry

**Comment by azerty9971** [comment]
This just doesn't make sense :/.

Could you share this specific device with my Tuya/Smartlife account: devun999999@gmail.com please?

I'll need to find out where the status is deleted and fix the bug.

Have a nice day,
Azerty

**Comment by fraizzo** [comment]
what do you need?

**Comment by azerty9971** [comment]
yes please

**Comment by fraizzo** [comment]
some news?

**Comment by azerty9971** [comment]
Is it the device "Sensore Garage"?
Because if so then it works fine on my end :/

![image](https://github.com/user-attachments/assets/f7687193-adfd-43e0-8f40-7b8b439ae058)

Do you have the cloud credentials in the integration? (https://github.com/azerty9971/xtend_tuya#adding-your-tuya-cloud-credentials)

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
If it is the same sensor what could happen is that you have another integration that is interfering with the device ...

Try to disable them and then re enable them one by one until you find the culprit...

I'll try to add some more debug logic that will ease in finding what is happening when I have a bit of time ;)

**Comment by fraizzo** [comment]
For your info, on tuya official integration the sensor works well.

**Comment by azerty9971** [comment]
Hello,
I'm not forgetting you, I'm cooking a way to find out what is happening ;)

Will keep you posted.

Have a nice day,
Azerty

**Comment by azerty9971** [comment]
Hello,
Once again I've made a debug build to fetch more information regarding this issue.

Could you update to 3.0.0-beta.13, restart HA and post here the full content of your system logs please?

Thanks in advance,
Azerty

**Comment by Ramon1347** [comment]
Hey, i have the same problem. If i use the tuya & xtend tuya integration the humidity gets missed. When i onla use the xtend Tuya integration the temp/Humid sensors only shows the temperatur. ANd i wanted to try it with the cloud, but when i enteredthe login data to configurate the integration it alwas shows: login_error.  Is there a way to use the temp/humi-sensors with the xtended tuya integration ?

![Screenshot 2024-11-11 123949](https://github.com/user-attachments/assets/b3802c8d-20ca-4ed9-bc63-e4e5a5d335b5)

**Comment by azerty9971** [comment]
Hello,
Can you see if this applies to you:
https://github.com/azerty9971/xtend_tuya/blob/main/docs/renew_cloud_credentials.md

And if not, then can you see if there is something you missed in the following procedure?
https://github.com/azerty9971/xtend_tuya/blob/main/docs/cloud_credentials.md

Have a nice day,
Azerty

**Comment by Ramon1347** [comment]
Hey,
with the cloud it works and update automatically as well. The only thing was, that i get the entity for the temperatur and humidity twice. So i neded to deactivated one, but now it is fine.

Thanks for helping :)

**Comment by azerty9971** [comment]
you're welcome :)
glad I could help ;)
